### ISSUE TITLE
Little form usability comments

### ISSUE THREAD

**Issue by FMCorz** [markn86/moodle-mod_customcert#1]
Hi Mark,

great job! I like the simplicity. I just find that the buttons "Save changes" and "Save changes an preview" seem associated to the file manager. So at first I wouldn't assume that I should click there.

The same applies for "Template" even though it looks a little more detached from the form.

If the only purpose of the "Upload image" is to select them in the image element, wouldn't it be better to have it in the element directly?

Cheers!
Fred

**Comment by markn86** [comment]
In the latest master (which I will push shortly) I moved the file manager to the image element, thanks for the suggestion. Not sure, where to put the 'Save template' header though.
