### ISSUE TITLE
Unable to Display Certificates

### ISSUE THREAD

**Issue by esmoyer** [markn86/moodle-mod_customcert#10]
This module is amazing and exactly what I am looking for but I cannot get it to display the certificates I get this error and debug code. I have done a lot of Googling and trial and error and unable to get it working. I have the Certificate and SimpleCertificate modules installed, would those be interfering? I hope this plugin is still maintained, it is too awesome to be abandoned! Any advice would be helpful. 

Can not find data record in database table customcert_issues.

More information about this error

Debug info: SELECT * FROM {customcert_issues} WHERE userid = ? AND customcertid IS NULL
[array (
0 => '134',
)]
Error code: invalidrecord
Stack trace:
line 1455 of /lib/dml/moodle_database.php: dml_missing_record_exception thrown
line 1431 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()
line 45 of /mod/customcert/element/code/classes/element.php: call to moodle_database->get_record()
line 292 of /mod/customcert/classes/template.php: call to customcertelement_code\element->render()
line 127 of /mod/customcert/view.php: call to mod_customcert\template->generate_pdf()

**Comment by markn86** [comment]
Hi Esmoyer,

Sorry I only just saw this issue.

This is a bug in the code. Thanks for pointing it out. Working on a fix now.

**Comment by markn86** [comment]
I pushed a fix which you can view at https://github.com/markn86/moodle-mod_customcert/commit/4931f4c607fe3ce0fb0f5d10f0f5bc64b87e6755.

Cheers for the report!

**Comment by esmoyer** [comment]
Hey Mark,​

No worries. Thank you for the fix, it is much appreciated!

Eric​
