### ISSUE TITLE
Add SVG support for image and bgimage elements.

### ISSUE THREAD

**Issue by Dave-B** [markn86/moodle-mod_customcert#100]
Currently, only the image and bgimage elements only use TCPDF's [Image()](https://tcpdf.org/docs/source_docs/classtcpdf/#a714c2bee7d6b39d4d6d304540c761352), which only supports raster formats.

TCPDF also provides [ImageSVG()](https://tcpdf.org/docs/source_docs/classtcpdf/#a56536508fb1b5aede7d2ed27f56c2353) for SVG support.

Pull request coming soon...

Support for EPS/AI _could_ be added via [ImageEps()](https://tcpdf.org/docs/source_docs/classtcpdf/#ace0583441eed657b827420fcfb37a3bd), but I don't think it's worth adding - I've not had great experience with it, due to its limited EPS compatibility.

**Comment by markn86** [comment]
Thanks Dave!

I recently noticed this support in TCPDF when fixing another issue but it escaped my attention and I never ended up creating a follow-up issue. So, thanks for doing that for me!

When creating your pull request please prepend the issue number (#100) before the commit message.

Thanks again!

**Comment by markn86** [comment]
(will add the issue number just letting you know for future sake :))

**Comment by markn86** [comment]
Done! 👍 Thanks again.
