### ISSUE TITLE
Activity backup doesn't include uploaded images

### ISSUE THREAD

**Issue by Dave-B** [markn86/moodle-mod_customcert#102]
Using the MOODLE_31_STABLE branch, creating and restoring a backup of a mod_customcert activity recreates the element settings, but didn't include the bgimage. Inspecting the contents of the .mbz file revealed it to contain no files at all.

This might be mitigated by a fix for #56.

**Comment by markn86** [comment]
Thanks Dave,

Working on this now.

**Comment by markn86** [comment]
Closing as done.

There is still an issue with backing up and restoring images that are in the system context due to a limitation on Moodles part. I may need to create a tracker issue and patch core to get that working. Needs more investigation.

Created #107.

Thanks Dave.

**Comment by mdjnelson** [comment]
Will be fixed in #298.
