### ISSUE TITLE
Add composer.json

### ISSUE THREAD

**Issue by michaelmeneses** [markn86/moodle-mod_customcert#103]

**Comment by markn86** [comment]
Can you expand on this? Why do you think this is necessary at this point in time? There are no dependencies here.

**Comment by michaelmeneses** [comment]
Allows to add the plugin as a dependency of Moodle

I will send the file.

Example
https://github.com/danmarsden/moodle-mod_attendance/blob/master/composer.json

**Comment by markn86** [comment]
Done, thanks Michael.
