### ISSUE TITLE
Certificate issue date is not working

### ISSUE THREAD

**Issue by sam-suresh** [markn86/moodle-mod_customcert#110]
[using this in Moodle 3.2.2]

I have a problem with Date. 

Although date in the setting is Completion Date, the date printed on certificate is the date certificate is downloaded. 

Moodle it clearly says "Issued Friday, 17 March 2017, 4:04 PM". 
But in certificate "30 April 2017". 

The module setting is completion date. 

(I also tried to issued date in the setting, still printing the date when the user download the certificate.)

**Comment by markn86** [comment]
Thanks for the report Sam. Will look into this once I have time.

**Comment by Dizolivemint** [comment]
We're also having an issue with the completion date. It populates with 'save changes and preview' but does not populate with 'Download Certificate'.

**Comment by Dizolivemint** [comment]
@sam-suresh Have you looked at your course completion settings?

**Comment by markn86** [comment]
Are you downloading the certificate on the report page?

**Comment by markn86** [comment]
Closing this as I think this is fixed now by #82 and I can not replicate it. Will release fix on plugins DB at the end of the week.

**Comment by jakubStep** [comment]
What about some countdown on the cert download page, to make dwnload buton available after some period?? There could be an option cronPeriod in the 
 custom cert settings, where you can setup minutes for countdown. On the end of the coundown, the download button will be available for download action. 

Thank you in advance for your support!
