### ISSUE TITLE
Emailing certificate task can cause additional issues to be created

### ISSUE THREAD

**Issue by markn86** [markn86/moodle-mod_customcert#111]
It has been reported that an additional row is inserted in the issues table causing duplicates for certain users.

**Comment by martinvivek** [comment]
Did you remember to make the first column something unique in your call to get_records? Duplicate value '480' found in column 'id'.
line 1184 of \lib\dml\mysqli_native_moodle_database.php: call to debugging()
line 280 of \mod\customcert\classes\certificate.php: call to mysqli_native_moodle_database->get_records_sql()
line 164 of \mod\customcert\classes\report_table.php: call to mod_customcert\certificate::get_issues()
line 1614 of \lib\tablelib.php: call to mod_customcert\report_table->query_db()
line 81 of \mod\customcert\report.php: call to table_sql->out()
Did you remember to make the first column something unique in your call to get_records? Duplicate value '480' found in column 'id'.
line 1184 of \lib\dml\mysqli_native_moodle_database.php: call to debugging()
line 280 of \mod\customcert\classes\certificate.php: call to mysqli_native_moodle_database->get_records_sql()
line 164 of \mod\customcert\classes\report_table.php: call to mod_customcert\certificate::get_issues()
line 1614 of \lib\tablelib.php: call to mod_customcert\report_table->query_db()
line 81 of \mod\customcert\report.php: call to table_sql->out()

**Comment by markn86** [comment]
Thanks.

I was able to replicate this, working on a fix now.

**Comment by markn86** [comment]
Fixed.
