### ISSUE TITLE
Course name not on cert send by email

### ISSUE THREAD

**Issue by r0bm1lls** [markn86/moodle-mod_customcert#112]
Hi - I have just enabled email sending on custom certificates for two courses. The email gets sent out but instead of the course name, the name of the site gets inserted. Rather embarrassing... this looks like a bug. 

Latest version released very recently. updated today

**Comment by markn86** [comment]
Thanks for the report. Will look into this shortly when I get spare time which will hopefully be in a couple of days.

**Comment by r0bm1lls** [comment]
Thanks, - Just clarify, the course name is correctly inserted when the cert. is downloaded using the activity.

**Comment by markn86** [comment]
This will be fixed by #82. It's the same issue.
