### ISSUE TITLE
Pick up a certificate outside the course?

### ISSUE THREAD

**Issue by frumbert** [markn86/moodle-mod_customcert#114]
I thought it might be possible to pick up certificates outside the course context, say on the "my" dashboard inside a block.

	$customcert = $DB->get_record('customcert', array('id' => $cmid), '*', MUST_EXIST);

		if (!$DB->record_exists('customcert_issues', array('userid' => $userid, 'customcertid' => $customcert->id))) {
			$customcertissue = new stdClass();
			$customcertissue->customcertid = $customcert->id;
			$customcertissue->userid = $userid;
			$customcertissue->code = \mod_customcert\certificate::generate_code();
			$customcertissue->timecreated = time();
			// Insert the record into the database.
			$DB->insert_record('customcert_issues', $customcertissue);
		}

	// ... then

		$link = new moodle_url('/mod/customcert/my_certificates.php', array('userid' => $userid, 'downloadcert' => true, 'certificateid' => $customcert->id));
		$downloadbutton = new single_button($link, $linkname);
		$downloadbutton->add_action(new popup_action('click', $link, 'customcertpopup', array('height' => 600, 'width' => 800)));
		$downloadbutton = html_writer::tag('div', $OUTPUT->render($downloadbutton), array('style' => 'text-align:center'));

but of course, now I realise that the elements are referencing the global $COURSE object to pull details (for instance customcertelement_coursename uses $COURSE->fullname).

Is it somehow possible to generate then pull a certificate for a user without first being in that course? Can I set the $COURSE global from the dashboard or something?

**Comment by markn86** [comment]
Hi Tim,

This is an issue I am solving now in #82. :)

We should not be using those globals, so will be getting rid of them as they are inaccurate (eg. My certificate page).
