### ISSUE TITLE
Missing date format in version 33

### ISSUE THREAD

**Issue by diane-villemure** [markn86/moodle-mod_customcert#116]
The 31 version of the plugin had the Month day, Year date format option (e.g., June 7, 2017). I upgraded to moodle 3.3 and the related customcert plugin (33_2017050503) no longer has that option. I'd appreciate if that date format was reinstated in future versions.

**Comment by markn86** [comment]
Thanks for the report Diane. I will add the options that were available, but no longer are, back to the activity.

**Comment by diane-villemure** [comment]
Thanks Mark. I'd appreciate if you'd let me know when the new version will be available.

**Comment by markn86** [comment]
I am going to work on this now, got time to kill before I have to head out. Will let you know when done.

**Comment by markn86** [comment]
Done. Will push to plugins DB shortly.
