### ISSUE TITLE
Add ability to delete issued certificates

### ISSUE THREAD

**Issue by markn86** [markn86/moodle-mod_customcert#119]
It makes sense that a teacher may want to revoke certificates from students due to various things (eg. found out student was cheating on the assignment).

**Comment by LuckyCyborg** [comment]
Singing along, imagine that the certification have a validity, for 5 years, for example...

Then we need (also?) the ability to expire/invalidate the certificate, in my opinion.

**Comment by markn86** [comment]
Ok, will be pushing a patch for this today.

@LuckyCyborg that sounds like another feature request. Please create a separate issue. :)
