### ISSUE TITLE
Extend element "User field" with custom profile fields

### ISSUE THREAD

**Issue by roennie91** [markn86/moodle-mod_customcert#120]
When you add an user field element to your certificate, you only have the option to select one of the default user fields. It would be nice if we could extend this selection with any custom profile field which can be defined via Site administration > Users > Accounts > User profile fields.

To clarify my thoughts about this feature, I've attached a screenshot.
What do yo think?
![screen shot 2017-06-29 at 11 38 34](https://user-images.githubusercontent.com/2242502/27681511-d52da4e4-5cbf-11e7-9cdb-1eee5cb3b477.png)

**Comment by roennie91** [comment]
Whoops, this feature already exists. I thought that I had custom profile fields configured but I looked at the wrong project (a)

**Comment by markn86** [comment]
No worries! Thanks for going to the effort of creating a report. Would rather more false positives than getting no reports at all. :)
