### ISSUE TITLE
Fails unit test when search not configured

### ISSUE THREAD

**Issue by mnods** [markn86/moodle-mod_customcert#125]
Hi, an FYI - installing into a test env to assess and the plugin failed - we haven't configured search.
3.1.6 (Build: 20170508)
17:32:21.904 PHP Fatal error: Class 'core_search\base_activity' not found in /opt/data/go-agent/pipelines/Moodle_Test/moodle/mod/customcert/classes/search/activity.php on line 36
17:32:21.904 
17:32:21.904 Fatal error: Class 'core_search\base_activity' not found in /opt/data/go-agent/pipelines/Moodle_Test/moodle/mod/customcert/classes/search/activity.php on line 36

**Comment by markn86** [comment]
This should not cause a failure even with search disabled. What version of Moodle are you running? Have you cleared your caches? It seems that Moodle can not find the base_activity files via the namespace, which it should regardless if search is enabled or not.

**Comment by mnods** [comment]
ignore me - problem with our set up - not failing unit test, but failing for another reason. 3.1  - cheers

**Comment by markn86** [comment]
Thanks for letting me know, closing this issue now.
