### ISSUE TITLE
Full Course name in e-Mail notification

### ISSUE THREAD

**Issue by awatzal** [markn86/moodle-mod_customcert#126]
By sending the course certificate from mod_customcert (moodle V3.3) to the participant is it possible to use in the e-mail body the text block emailstudentbody. The course full name should appear in the text. For this I use the variable {$a-> coursefullname}. Unfortunately, the course short name is displayed in the email not the course full name. There are existing a second variable {$a->coursename}, but this also show the course short name.
I think this is a bug, of cause bouth variables display the course short name.

Please fix that, so that the variable {$a-> coursefullname} display the course full name in the email.

In the preview certificate plugin is it able to output the course full name by using the variable {$ a-> course} in the mail body. However, this does not work in the new plugin Custom certificate 3.3 release (Build: 2017050505)

**Comment by markn86** [comment]
There was another request to be able to set the institution name.

I am going to take a look at this when I get some free time to work on this.

**Comment by markn86** [comment]
Sorry for the delay. Got some free time this weekend, so working on a few issues. This will be fixed in next release.
