### ISSUE TITLE
Hard-wired English language strings

### ISSUE THREAD

**Issue by germanvaleroelizondo** [markn86/moodle-mod_customcert#13]
Hi,
This is a very nice and useful plugin. (I already translated the English language strings into Mexican Spanish). It will certainly be used a lot at my University site.

I think this plugin will be even nicer if all English language strings were declared as variables, so that they can be translated in AMOS.

The followin strings seem to be hard-wired in English:

Border, Category name, Code, Course name, Date, Grade, Grade item name, Image, Student name, Teacher name, Text, User field

Thanks in advance for your help.

**Comment by markn86** [comment]
Hi,

Actually, these strings are not hard-coded, they are just stored in a separate language file which may have caused some confusion. All those items in your list you are referring to are elements of the certificate. Please see mod/customcert/element for a list. These folders all contain a language file in lang/en.

Cheers!

**Comment by markn86** [comment]
I should also mention that elements are sub-plugins so behave similar to other plugins in Moodle (can contain a lang file, db/access.php, db/install.xml etc).

**Comment by germanvaleroelizondo** [comment]
Hi Mark,
Indeed, I apologize. I see there are 49 more English language strings at AMOS for these sub-plugins. I will translate them shortly.
Thanks a lot.
Cheers!

**Comment by germanvaleroelizondo** [comment]
Hi Mark.
I am afraid I do not understand 3 English language strings and I can not translate them:

numbersuffix_nd | customcertelement_date (nd);

numbersuffix_rd | customcertelement_date (rd);

numbersuffix_st | customcertelement_date (st)

**Comment by markn86** [comment]
Hi German,

Sorry, I didn't consider how easy they would be to translate for other languages. In fact they may not even be applicable.

1st
2nd
3rd
4th

Those values after the integer are what they refer to. I also realised that we are not translating 'th' at all.

**Comment by markn86** [comment]
You can see their usage in mod/customcert/element/date/classes/element.php in the function get_ordinal_number_suffix().

**Comment by germanvaleroelizondo** [comment]
Thanks Mark. 

I'll be looking forward to using your plugin with some real world data and see if my translation works as intended.

**Comment by germanvaleroelizondo** [comment]
Hi.

Would it be too difficult for you to re-write some of your code as to replace (st) with (1st), (nd) with (2nd) and (th) with (n~th)?.

I imagine it would be easier for most language translators to translate the complete word (1st) instead of just the (st) part.

Maybe this just a very small issue and we need not ask David Mudrak for his advise (as he is also a maintainer for a foreign language), but I would guess that, for example, the French-speaking Moodlers will deffinitively want to translate your great plugin into a grammatically correct French version :)

**Comment by markn86** [comment]
Sorry for getting back to you so late - this issue was closed so I forgot to address it. Are you able to create another separate issue for your last request so we have a clean history?
