### ISSUE TITLE
Declared globals into customcertelement_date/classes/element.php

### ISSUE THREAD

**Issue by mauriciocarnieletto** [markn86/moodle-mod_customcert#131]
Hi,

Can you please add this corrections at "customcertelement_date/classes/element.php"?

`if(!defined('CUSTOMCERT_DATE_ISSUE'))
define('CUSTOMCERT_DATE_ISSUE', '-1');

/**

Date - Completion
*/
if(!defined('CUSTOMCERT_DATE_COMPLETION'))
define('CUSTOMCERT_DATE_COMPLETION', '-2');
/**

Date - Course start
*/
if(!defined('CUSTOMCERT_DATE_COURSE_START'))
define('CUSTOMCERT_DATE_COURSE_START', '-3');
/**

Date - Course end
*/
if(!defined('CUSTOMCERT_DATE_COURSE_END'))
define('CUSTOMCERT_DATE_COURSE_END', '-4');`

**Comment by markn86** [comment]
Can you please explain why you need these changes?

**Comment by mauriciocarnieletto** [comment]
Hi Mark!

 Cause when we have the "display_errors = on", the pdf lib that the plugin uses, can't handle with pre outputed data.

![error](https://user-images.githubusercontent.com/4827003/29213617-5d381d70-7e7a-11e7-9ed2-cd65b738f502.png)

 When the user put two dates into the certificate, the plugin is trying to declare those globals again.

![structure](https://user-images.githubusercontent.com/4827003/29213652-7b5acc12-7e7a-11e7-9285-c19bcea99308.png)

 Here is how it is

![without](https://user-images.githubusercontent.com/4827003/29213671-9a6d70a0-7e7a-11e7-8977-9422683baaed.png)

 Here is how it's gonna be after the correction

![with](https://user-images.githubusercontent.com/4827003/29213681-a81a06fa-7e7a-11e7-9b6c-1c5a8e3afb77.png)

**Comment by markn86** [comment]
Thanks for the report.

Would this also be an issue with the 'grade' element?

When I get time I will try and replicate this.

**Comment by markn86** [comment]
Sorry, I can not replicate this issue. I have display errors on with full debugging mode. What version of the plugin are you use?

**Comment by markn86** [comment]
Also, what PHP version?

**Comment by mauriciocarnieletto** [comment]
Did you add two dates fields?



*Maurício Francisco Carnieletto*  Software Composer & Music Developer
[image: photo] Phone: (41) 98492-8785 <+5504198492-8785>
Email: mauricio.carnieletto@gmail.com
Website: https://about.me/mauricio.carnieletto
<http://about.me/mauricio.carnieletto>
<http://www.facebook.com/mauricio.carnieletto>
<http://br.linkedin.com/in/mauriciocarnieletto>
<http://plus.google.com/u/0/+MaurícioCarnieletto/>
<http://www.youtube.com/channel/UCR1cpbRH_8KjAiQPcZqwNeQ>

**Comment by markn86** [comment]
Yep.

Are you able to tell me the version of the plugin and PHP version please? :)

**Comment by markn86** [comment]
Closing this as I can not replicate and no one else has experienced this issue afaik. It would surely be a common case to add 2 or more date values to a certificate so I would expect this to have been reported multiple times.
