### ISSUE TITLE
Allow users to load a template but do not allow them to modify it

### ISSUE THREAD

**Issue by markn86** [markn86/moodle-mod_customcert#137]
It makes sense that you would want a site template for teachers to use, but may not want them to make any changes.

**Comment by markn86** [comment]
Closing this, the more I think about it the less it makes sense. No other activities have restrictions as such, and if the teacher can modify items in a course then they should be able to modify any other activity.

**Comment by markn86** [comment]
No other activity does anything similar to this, so a bit hesitant to work on it. However, if we were to do something similar the best way I think would be to add another capability, like 'mod/customcert:loadtemplate' which lets a user load templates, and then prevent the permission ''mod/customcert:manage'.

**Comment by abias** [comment]
On request by @dmitriim, I am adding some background information to this issue:
* Currently, as admin, I can create global templates which users can load in their activity instances.
* Currently, mod/customcert:manage controls multiple aspects of this activity plugin, including the fact that a user can load existing global templates into their activity instances and modify these loaded templates within their activity instances.
* As admin, I want to specifically control which users are able to modify a template within an activity instance and I can't do this yet as mod/customcert:manage is some kind of multi-purpose capability.
* As admin, I want to to separate two possible kinds of users:
1. A user wo can load a global template within an activity instance and who can modify it afterwards within the activity instance. This user will be able to add new elements to the template as well as edit / delete existing elements.
2. A user wo can load a global template within an activity instance but who can only use it unmodified within the activity instance. The user will not be able to add / edit / delete any elements within the template.
* Adding / editing / deleting of elements is always meant to happen in the activity context. Users should never be able to modify the global template.
* The fact that a user can / cannot create his own template within an activity instance is not covered by this issue. This is handled in #181.

**Comment by abias** [comment]
This issue is superseded by #227 and shouold thus be closed.

**Comment by markn86** [comment]
Closing.
