### ISSUE TITLE
Some English strings are to difficult to translate (for lack of context)

### ISSUE THREAD

**Issue by germanvaleroelizondo** [markn86/moodle-mod_customcert#14]
Hi Mark,

I like your custom certificate a lot.

But when I was translating it's sub-plugins into Mexican Spanish, I ran into a problem:

numbersuffix_nd | customcertelement_date 'nd'
numbersuffix_rd | customcertelement_date 'rd'
numbersuffix_st | customcertelement_date 'st'

Which you previously explained to me that are used for '1st', '2nd' and '3rd'... are just too difficult for a non-native English user (such as myself and many other Moodle translators) to guess properly in order to translate accurately.

Would it be too difficult for you to change your code, so as to have Strings for '1st', 2nd' and ...
this one is difficult ... '{$number}th' ?

I realize this is an odd request, but I sincerely think that this would make it so much easier to properly translate your extremely useful plugin into several more languages.

Thanks in advance for your help.

**Comment by markn86** [comment]
Hmm, I have been thinking about this.

If we were to translate you would want it to be something like

$string['1st'] = "1st";
$string['2nd'] = '2nd';
$string['3rd'] = '3rd';
$string['4th'] = '4th';

Correct?

If so, that makes it a bit more difficult. Say the date was the 22 I would then want to add the suffix (in this case 'nd') but with the above translations it would become 222nd, so there would have to be some logic involved so this didn't happen.

**Comment by germanvaleroelizondo** [comment]
Hi Mark.

It seems to me that the English language has some peculiar rules for naming numbers that make translations a bit too difficult.

What would you think of using plain numbers (eg, 2 instead of 2nd) ? 

Or using the date format from the OS, as it works in the Moodle calendar?

Or, maybe just name your variables in a way that it is very easy to guess what the (st, nd, rd, th) meaning is ? I think this might be the most straightforward and quickest solution :)

numbersuffix_st_as_in_first
numbersuffix_nd_as_in_second
numbersuffix_rd_as_in_third

**Comment by markn86** [comment]
Thanks for the report. I ended up changing the string index so it made it more obvious to translators. :)

**Comment by scara** [comment]
Hi @markn86,
should the commit message be amended to include an AMOS script too (`MOV`)? More at https://docs.moodle.org/dev/Automated_Manipulation_of_Strings_2.0#AMOS_script.

HTH,
Matteo

**Comment by markn86** [comment]
As much as I hate re-writing history, you are right. Fixing now.

**Comment by scara** [comment]
TNX!
Appreciated, included all your hard working in the Moodle-land :+1: :smile:.

**Comment by germanvaleroelizondo** [comment]
Thanks for making the strings (names) easier to understand and translate properly, in order to avoid errors  :)

This plugin is very used world-wide with many languages additional to English.
