### ISSUE TITLE
Add text to My Certificates page

### ISSUE THREAD

**Issue by emmarichardson** [markn86/moodle-mod_customcert#140]
Having placed a very nice link on my Front page to the My Certificates page (which I love!), my teachers (bless their hearts!!!!!) now find it confusing that their continuing education certificates do not show up their automatically when they have completed the prerequisites for a course.  It would be wonderful if we could put some text on that page explaining that they have to download the certificate from the course page first!

**Comment by markn86** [comment]
Hi Emma.

Are you aware of the 'Email students' option? (see https://docs.moodle.org/32/en/Custom_certificate_module#Email_students.2Fteachers.2Fothers)

This will mean that the certificates are automatically emailed (when Moodle cron is run) meaning users will receive their certificates as well as have them issued at the same time.

**Comment by emmarichardson** [comment]
Yes, I did see that but I am right in thinking that they still have to click on the Download Certificate for it to be “issued”?

Emma


Emma Richardson
Distance Learning Coordinator
Direct: 719-650-3037

On Oct 9, 2017, 5:19 AM -0600, Mark Nelson <notifications@github.com>, wrote:

Hi Emma.

Are you aware of the 'Email students' option? (see https://docs.moodle.org/32/en/Custom_certificate_module#Email_students.2Fteachers.2Fothers)

This will mean that the certificates are automatically emailed (when Moodle cron is run) meaning users will receive their certificates as well as have them issued at the same time.

**Comment by markn86** [comment]
Yep, it issues the certificate as well.

**Comment by markn86** [comment]
Add message, will be available in next release.
