### ISSUE TITLE
Grade item uses 'gradeitem:XYZ' in SQL query causing exception to be thrown

### ISSUE THREAD

**Issue by pixliacik** [markn86/moodle-mod_customcert#149]
when I try to download certificate, i get error "Invalid course module ID"

**Comment by pixliacik** [comment]
I'm using moodle 3.3 with Aardvark theme

**Comment by pixliacik** [comment]
Debug info: SELECT * FROM {course_modules} WHERE id = ?
[array (
0 => 'gradeitem:159',
)]
Error code: invalidcoursemodule

**Comment by pixliacik** [comment]
Stack trace:

    line 1533 of /lib/dml/moodle_database.php: dml_missing_record_exception thrown
    line 1509 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()
    line 81 of /mod/customcert/element/gradeitemname/classes/element.php: call to moodle_database->get_record()
    line 303 of /mod/customcert/classes/template.php: call to customcertelement_gradeitemname\element->render()
    line 144 of /mod/customcert/view.php: call to mod_customcert\template->generate_pdf()

**Comment by markn86** [comment]
Thanks for the report.

Geez, that query is completely wrong (using 'gradeitem:159'), that is bad. Have you tried editing the element and then resaving?

**Comment by pixliacik** [comment]
Hi, i didn't change anything, because I'm not friendly with coding, so I'm not sure what to change.

**Comment by markn86** [comment]
You can just edit the element, then resave it. No need to attempt to change any code.

**Comment by pixliacik** [comment]
Hi, I do not know how to edit the element :(

**Comment by markn86** [comment]
Click on the 'edit' icon next to the element name, then click 'save'.

**Comment by markn86** [comment]
Closing as no one else has reported this issue and I have not got a response.
