### ISSUE TITLE
'Add page' option causes fatal error

### ISSUE THREAD

**Issue by thepurpleblob** [markn86/moodle-mod_customcert#154]
Build 2017050509

Brand new install of the module in latest Moodle 3.3. Have done nothing else so far. 

From admin > plugins > customcert, go to the templates page. Click the 'Add page' link towards the bottom right. 

```
A required parameter (contextid) was missing

More information about this error

×Debug info: 
Error code: missingparam
×Stack trace:
line 503 of /lib/setuplib.php: moodle_exception thrown
line 568 of /lib/moodlelib.php: call to print_error()
line 45 of /mod/customcert/edit.php: call to required_param()
```

**Comment by markn86** [comment]
Thanks for the report.

I can confirm this is a bug.

You can only add the page once the template has been created (basically you need to click 'Save changes' so the actual template is added to the database).

**Comment by markn86** [comment]
Created fix, thanks.
