### ISSUE TITLE
pdf generation not working

### ISSUE THREAD

**Issue by omnempathy** [markn86/moodle-mod_customcert#157]
Hi,
A couple of weeks back an unusual problem appeared. The custom certificate is no longer generated. A 500 error appears in Chrome whilst Safari and Firefox exhibit only a blank page. Has this been noted before as an issue?
I suspect it has to do with the execution to generate a PDF but really can't be sure. 

If I try to uninstall/reinstall the plug-in will previous certificates on all courses have to be recreated?

Thanks!

**Comment by markn86** [comment]
Can you check your apache logs or turn on debugging mode in Moodle (https://docs.moodle.org/34/en/Debugging) to see if there is any more information you can provide?

**Comment by omnempathy** [comment]
Debugging is set to developer but to be honest with you i am not sure how or where to access the debugging log

**Comment by markn86** [comment]
You can choose to get it to display on the screen if you are unsure where your log file is.

**Comment by omnempathy** [comment]
cheers - ok, aside from some general warning on pages about the swf player being missing - here is the script from the error page that comes up when asking for the certificate to be generated...

Warning: require_once(/home/echo3co/public_html/learning/lib/tcpdf/tcpdf.php): failed to open stream: No such file or directory in /home/echo3co/public_html/learning/lib/pdflib.php on line 149

Fatal error: require_once(): Failed opening required '/home/echo3co/public_html/learning/lib/tcpdf/tcpdf.php' (include_path='/home/echo3co/public_html/learning/lib/pear:.:/opt/alt/php56/usr/share/pear:/opt/alt/php56/usr/share/php') in /home/echo3co/public_html/learning/lib/pdflib.php on line 149

**Comment by markn86** [comment]
What version of Moodle are you using?

**Comment by omnempathy** [comment]
3.2.2

**Comment by omnempathy** [comment]
SOLVED. It seems this is the result of a malware attack. tcpdf.php had been renamed to tcpdf.php.suspected - a recognised hacker behaviour. Thanks for your help in steering me to the cause!

**Comment by markn86** [comment]
Glad you got this sorted and hope there was no damage to your server. Good luck investigating!
