### ISSUE TITLE
Fatal error: Can't use method return value in write context

### ISSUE THREAD

**Issue by luisvahosh** [markn86/moodle-mod_customcert#158]
1. Install the plugin from the moodle website
2. He perfectly updated the database
3. And the application is installed
4. When I generate a certificate, it goes blank.
5. entry to edit the certificate and I get that error

Greetings install the plugin in moodle 3.1 and to modify the certificates the page is blank
In debug mode this is the error

http://www.waylearn.co/app/mod/customcert/edit.php?tid=1

Fatal error: Can't use method return value in write context in /home/luisvahos/public_html/app/mod/customcert/element/border/classes/element.php on line 109

**Comment by markn86** [comment]
Hi Luis,

Sorry I am unable to reproduce this error.

What version of PHP are you using? What version of the plugin are you running (can be found in mod/customcert/version.php)?

**Comment by markn86** [comment]
After a bit of googling I am almost sure this is an issue with the version of PHP you are using.

The problem is `$this->get_data()` in an `empty()` check. The solution is to assign the variable before performing the conditonal check.

I'll come up with a patch soon.

**Comment by luisvahosh** [comment]
defined('MOODLE_INTERNAL') || die('Direct access to this script is forbidden.');

$plugin->version   = 2016052319; // The current module version (Date: YYYYMMDDXX).
$plugin->requires  = 2016052300; // Requires this Moodle version (3.1).
$plugin->cron      = 0; // Period for cron to check this module (secs).
$plugin->component = 'mod_customcert';

$plugin->maturity  = MATURITY_STABLE;
$plugin->release   = "3.1 release (Build: 2016052319)"; // User-friendly version number.

**Comment by luisvahosh** [comment]
Thank you very much if it was the PHP version is already working correctly

**Comment by markn86** [comment]
Hi Luis, do you mean it *was* working before prior to the update? Are you able to tell me what PHP version you are running? You can find this in 'Site administration' > 'Server' > 'PHP Info'.
