### ISSUE TITLE
Allow verification of deleted users

### ISSUE THREAD

**Issue by pjonker** [markn86/moodle-mod_customcert#159]
Mark compliments for this plugin works perfectly. One suggestion for the verification. Noticed that unenrolling and suspending a user still gives the opportunity to verify which is great. However deleting the user account breaks it and gives the warning 'Not verified'. Would you be able to store the user Fullname and Coursename in a separate table on issuing the certificate. This way the verification proces will also work once the user has been deleted.

**Comment by markn86** [comment]
This didn't require any storing of extra information as the user is still present in the Moodle database when you perform a soft delete (just deleting them via the UI). However, if the user requests to be deleted via the GDPR functionality this won't work as all their data will be removed (rightfully so).
