### ISSUE TITLE
Category Grade fields for Certificate instead of Course Total or Activities. 

### ISSUE THREAD

**Issue by Ambershay** [markn86/moodle-mod_customcert#161]
Hi there. I was wondering how we could display the category total in the "Grade" element of the certificate. Currently, the only options are "Course Grade" and "Graded activity items" within a topic. We offer a custom certificate for each topic of the course and the grade is separated by course categories. Is this something I can enable in Moodle or is this a query we could implement on the certificate in a near future update?
![grade](https://user-images.githubusercontent.com/11494177/35655112-6d18e844-06ad-11e8-8c31-6aea4921be9c.jpg)

**Comment by Ambershay** [comment]
Hi all. Just wondering if anyone had any idea if the "Catalog Total" grade would be added to the dropdown above? Many thanks! --Justin

**Comment by Ambershay** [comment]
Hi there. Just wondering if there's a better forum for questions? We really like the plugin, but we need to be able to use the category total instead of the grade total for certificates. At least the option to use either.

**Comment by markn86** [comment]
Hi @Ambershay, sorry for not replying. I work on this in my free-time so don't get the opportunity to work on new features as much as I would like. I would happily review a patch if someone was to provide one, but for now this needs to wait until I have time to work on it. I am super busy with the Moodle 3.5 upcoming release and most my dev work is spent working on core.

For general support you can post in https://moodle.org/mod/forum/view.php?id=7163.

**Comment by Ambershay** [comment]
Totally understand! Thank you so much for getting back to me. Would be awesome if we can make this happen, but I totally understand you’re slammed. 

--Justin

**Comment by Ambershay** [comment]
Just wanted to keep this front and center.  Would be great to utilize category total in addition to course grade. We have a National Apprenticeship certification that get's certificates based on category topics rather than course total. Many thanks!

**Comment by Ambershay** [comment]
Hi Mark. Is there ANYWAY we can give this some attention? In my mind it's just a database entry. All I'm asking is if we can have the ability to assign category total in addition to course grade when we offer certificates. Currently for our National Apprenticeship Program for HVAC we have to manually create certificates for each of the 4 years when they complete a category,  but utilize this plugin overall. It's a waste of labor because this plugin could be used at all times with NO manual effort. Please let me know. I think I first created this ticket a year ago. Many thanks.

**Comment by markn86** [comment]
Hey Amber, I've added this to my list of things to do before I put out the next release. I just released a new version yesterday, so not sure when the next release will be (I am adding important issues to a list). I do work on this in my spare time so I can't really tell you when that will be, but it's now on the list and will get attention.

**Comment by markn86** [comment]
Hi @Ambershay, what version of the plugin are you using and what version of Moodle?

**Comment by markn86** [comment]
I created a grade category and it was listed in the drop-down, and looking at the code this has been supported since #98.

<img width="663" alt="screen shot 2018-07-15 at 6 01 44 pm" src="https://user-images.githubusercontent.com/783213/42732748-309b1648-8859-11e8-992f-eb6fefa6e5d0.png">

**Comment by Ambershay** [comment]
Good morning Mark,

We’re currently using Moodle 3.1.13, so whatever the latest certificate build was at the time.

What we need is the option for “Category Total”. So when we go into the grade book, we have the option to create new categories and then sort the learning activities into those different graded categories. What the certificate doesn’t (or didn’t) allow was for us to select a category total from the drop down. You can see this in the original screen shot I provided.

If you’re saying this is now available, great! I’ll download the latest and have it installed. Many thanks!

--Justin

**Comment by markn86** [comment]
This was added in 3.1.17. Closing, thanks! Best to always keep your plugin up-to-date (though I am no longer support version 3.1).

**Comment by Ambershay** [comment]
Okay thank you!

--Justin
