### ISSUE TITLE
Student cannot view certificate

### ISSUE THREAD

**Issue by jdo202** [markn86/moodle-mod_customcert#164]
Problems with Custom Certificate in Moodle; after a user has finished to read the lesson and has a quiz result of 100%, he cannot view nor print his certificate when access is restricted to “students must match: Grade of QUIZZ must be > 30%”. **I cannot find the error**

**These are some of the Course settings:**
-	Format: topics format
-	Hidden sections are shown in collapsed form
-	Course layout: show all sections on one page
Completion tracking: YES
Groups: No groups

**In Topic 1, there are the following activities**
a.	One lesson with two “pages” whose name is Einführung
b.	A quiz
c.	A certificate for those who cumplen 

**Settings of the lesson “EINFÜHRUNG”:**
-	Name of the lesson
-	Description of the lesson
-	Appearance: no progress bar, no display menu
-	Avaibility: 12 feb 2018-13 march 2018
-	No time limit
-	Flow control: no student review, 1 max attempts
-	Grade: Type Point, max grade 10, grade category: uncategorized, grade to pass 5, NO practice lesson, NO retakes allowed
-	Restrict access: NO
-	Activity completion: 
o	ACTIVATED: Show activity as complete when conditions are met
o	ACTIVATED: Students must view a grade to complete this activity
o	Expect completed on 13 march 2018
-	Competencies: no selection

**Some of the Settings of the activity Custom Certificate**
-	Name of the Certificate
-	Options: none
-	Restrict access: students must match: Grade of QUIZZ must be > 30%
-	Activity completion: show activity as complete when conditions are met, student must view this activity to complete it; expect completed on 13 march 2018
-	Competencies: no selection; upon activity completion: do nothing

Does anybody find the error? Thank you

**Comment by emmarichardson** [comment]
This is not a custom certificate bug - this should just be on the forums.  You have something wrong in your settings or cron is not running.  I responded to you on the forum.

**Comment by markn86** [comment]
Thanks Emma, closing.

**Comment by emmarichardson** [comment]
No problem. Hopefully it will give you more time to look at the URL bug!! 😀
