### ISSUE TITLE
Feature request: Option to choose in whose name the certificate is sent from

### ISSUE THREAD

**Issue by Jarvil** [markn86/moodle-mod_customcert#165]
Hello,

I would like to see an feature in the Certificate options that lets you choose in whose name the email copy of the issued certificate is send. At the moment it's send in the name of the teacher who has the oldest user account in Moodle which I find little bit inconsistent way to do it.

**Comment by tbahula** [comment]
Yes, please! In fact, We'd prefer to have it use the same approach as other Moodle notifications (such as the Forum digest), since the certificate notification comes from an unmonitored email address.

**Comment by anieminen** [comment]
Hi,

Moodle core approach is to use the `allowedemaildomains` setting with all outgoing email: [https://docs.moodle.org/36/en/Mail_configuration#Outgoing_mail_configuration](https://docs.moodle.org/36/en/Mail_configuration#Outgoing_mail_configuration).

If the setting is empty, email should always be sent from no-reply address set in site configuration.

**Comment by markn86** [comment]
Hey guys, thanks for commenting. I wholeheartedly agree that the current approach is not ideal. I've put this in to-do list for the next release.

**Comment by markn86** [comment]
Ok, setting it so it is the noreply user, which is standard throughout all of Moodle.

**Comment by Jarvil** [comment]
Still I would like to see an option to choose it.

**Comment by markn86** [comment]
That can be done in a follow-up. Right now I am just triaging and addressing basic changes in preparation for about a months time where I will get time to do these. There is already an issue about specifying the user.

**Comment by markn86** [comment]
I created #278.
