### ISSUE TITLE
Certificate url corrupts when copied to a new course

### ISSUE THREAD

**Issue by emmarichardson** [markn86/moodle-mod_customcert#166]
I use icons in labels to connect to our activities/certificates etc.  I have noticed that when I restore the course to another course, the url for the custom certificate changes to read: https://mydomain/course/$@customcertVIEWBYID*3037@$ which is still referencing the old certificate id and not actually a real link.  This behavior does not happen for any of my other activities.

**Comment by markn86** [comment]
Hi Emma,

It would be great if you could write some replication steps.

Are you just copying the URL of the certificate (for example http://yoursite/mod/customcert/view.php?id=4) and putting this in the label description then performing a backup/restore?

**Comment by emmarichardson** [comment]
Add custom certificate activity to a course.
Create a label with an image.  Select image.  Click on Link in atto toolbar.  Link the image to the custom certificate activity (by copying and pasting the link to the custom cert activity - full link including domain).  
This part all works great!

Backup course and restore to a new course.
Image link is now corrupted.

Same exact process with other kinds of activities work as expected and now link to the newly created activities in the restored course.

**Comment by markn86** [comment]
Ok, created a fix. I will update version 3.3 and 3.4 in the plugins DB shortly.

**Comment by emmarichardson** [comment]
Thanks Mark!!
