### ISSUE TITLE
Settings Request: Hide "download table data" option

### ISSUE THREAD

**Issue by snarsnartheworkalien** [markn86/moodle-mod_customcert#168]
Hello,

Our students are REALLY not tech savvy. They are trying to download PDF copies of their certificates using the "Download table data" with the Download button.

If you could just put a unique class name on that section, then I could hide it with CSS. Thank you.

![screen shot 2018-02-15 at 12 26 37 pm](https://user-images.githubusercontent.com/26467438/36279319-9122ff6e-124b-11e8-8fcc-382a046308ac.png)

**Comment by markn86** [comment]
Sorry for the long delay in response.

I am just going through the backlog now. Recent updates have been heavily focused on certain areas and I haven't been able to look at the backlog of issues.

Unfortunately this is an issue with core. Via the API I can't add any unique styles (this is using `table_sql`) easily. To do this I would have to overwrite the template `core/dataformat_selector` in my plugin which is really quite over-kill to add a class to the download button.

You could always use `#page-mod-customcert-my_certificates .dataformatselector` to achieve this.

HTH,

Mark
