### ISSUE TITLE
Certificate does not respect multilang

### ISSUE THREAD

**Issue by markn86** [markn86/moodle-mod_customcert#170]
1. Install the Russian language pack.
2. Enable the filter 'Multi-Language Content'.
3. Add a text element and for the 'Text' field add ```<span lang="en" class="multilang">Title EN</span><span lang="ru" class="multilang">Zazdarovje RU</span>```.
4. Save the element.
5. Notice when re-positioning the element it is not filtered.
6. Notice when downloading the PDF it is not filtered.

**Comment by markn86** [comment]
List of elements this affects -

1. Category name.
2. Course name.
3. Grate item name.
4. Text.
5. User field.

**Comment by michael-milette** [comment]
I am experiencing the same issues. The elements need to be processed through Moodle's format_text() or format_string() functions before they are displayed. For more information on how to use these functions, see https://docs.moodle.org/dev/Output_functions.

**Comment by markn86** [comment]
Thanks for bumping this. I did the investigation but never got round to coding it as other things took priority by the time I got round to being able to do any code for this plugin.

**Comment by michael-milette** [comment]
Thank You Mark! Much appreciated :-)
