### ISSUE TITLE
Manager role included where Teacher role specified

### ISSUE THREAD

**Issue by tbahula** [markn86/moodle-mod_customcert#171]
We're using Moodle 3.1.9 (Build: 20171113) with Custom certificate plugin 3.1.20 (Build: 2016052320).

We are having two problems that seem like they might be related. The problems happen in a course with 1 user enrolled as a teacher and several users as students.

The first problem is more of an annoyance. When adding a Teacher name element to the certificate (or editing it), the dropdown list also includes Managers with permissions to the course inherited from the course category.

![image](https://user-images.githubusercontent.com/14959510/37364805-ed08634c-26d1-11e8-960c-920515ad2b82.png)
![image](https://user-images.githubusercontent.com/14959510/37364925-3c9328de-26d2-11e8-99b6-6d321c33cc74.png)

The second problem is more troublesome and might be related. When Email teachers is enabled, Managers with permissions to the course inherited from the course category also receive an email.

**Comment by tbahula** [comment]
Interesting to note that the Certificate module has Capabilities/mod/certificate:printteacher 'When assigned at the module level, these user names will be printed on the certificate as "teacher".' Similar functionality would be useful in Custom certificate.

**Comment by markn86** [comment]
Sorry for the delay in looking at this. I am just going through the backlog now.

I will deal with the first problem in the release after next.

**Comment by markn86** [comment]
Actually, since this is related to #176 and I am putting that in the next release I will put this one in as well.

**Comment by markn86** [comment]
Pushed fix, thanks!
