### ISSUE TITLE
Possible race condition when issuing certificates

### ISSUE THREAD

**Issue by bynare** [markn86/moodle-mod_customcert#173]
The scheduled task retrieves all the issued certificates before starting to process ones that have not been issued yet. Because of this, it is currently possible for a certificate to be issued via the UI (view.php), after the scheduled task has fetched the currently-issued certs, while issuing new certificates.

**Comment by markn86** [comment]
I will be updating the plugin on the plugins DB this week with this fix + GDPR compliance.
