### ISSUE TITLE
MOODLE 2.9 ERROR - Blank Page

### ISSUE THREAD

**Issue by ambokeso** [markn86/moodle-mod_customcert#175]
Please HELP. MOODLE 2.9 / PHP Version 5.6.33
- downloaded - 2.9/3.0 release (Build: 2016032202) (2016032202)Moodle 2.9, 3.0 - ok
- Installed as administrator on moodle site. - ok
- customized template. ok
- downloaded and previewed pdf. - ok
- ERROR - Blank page in course (Get your custom certificate)
TIA

**Comment by markn86** [comment]
Please enable debugging on your site so that the error message is displayed. I am also closing this issue as I am no longer supporting Moodle 2.9, please upgrade to a newer version (2.9 has known security issues, you should really really upgrade).
