### ISSUE TITLE
digitalsignature not displayed Moodle 3.4.2

### ISSUE THREAD

**Issue by kenjlacey** [markn86/moodle-mod_customcert#178]
I have added a custom certificate, 3.4 (2017111300),  to a course Moodle 3.4.2+ (Build: 20180412) running on Fedora 27, PHP 7.1.
The elements in order are Background image, Signature image, Course name, Student name, Code and date.
The signature appears in the Reposition elements preview infront of the background image and can be moved to the required location. Both images have a transparent background.
The Signature element is not produced on the saved PDF.
Tested using Firefox on Centos 7, Friefox and Chrome on Windows 7

**Comment by markn86** [comment]
Hi Ken,

Are you able to attach the image you are using that is not working?

**Comment by markn86** [comment]
I also wonder if the same happens if you were to use the `image` element with the image you are using from the `digitalsignature` element. I imagine it does. To replicate this it would be great to get the background image and the image you are using to display on-top of it, as I have been unable to reproduce it..

**Comment by kenjlacey** [comment]
Hi Mark

I should have closed this. I had added an image of signature in the digital signature element.
It works for me as per below using the image element.
Having a transparency property for the image element would be a great feature.
The custom cert is a great plugin as I will have different certs for each course.
I had modified the certificate plugin to do similar but the custom certificate is far superior.

![cert elements](https://user-images.githubusercontent.com/38467097/42622611-48225c00-85b0-11e8-8521-953ef118e152.png)
[Safe_from_Harm_Certificate.pdf](https://github.com/markn86/moodle-mod_customcert/files/2187830/Safe_from_Harm_Certificate.pdf)
Regards
Ken

**Comment by markn86** [comment]
Thanks Ken!

Sorry for getting back to you so late. I have been working on mobile support for this plugin which did take some time from me getting to look at the backlog of bugs. I am just slowly doing that now.

I was going to point you to #186 but see that you are the reporter hehe.
