### ISSUE TITLE
Add possibility to selectively disable activity instance settings

### ISSUE THREAD

**Issue by abias** [markn86/moodle-mod_customcert#179]
When adding a mod_customcert instance to a course, a teacher is offered several options:
* Email students
* Email teachers
* Email others
* Allow anyone to verify a certificate
* Required minutes in course
* Set protection 

We propose to add a possibility to selectively disable these activity instance settings, e.g. if an admin does not want to allow teachers to use the "Email others" feature.

This can be achieve with two possible strategies:
1. Add an admin setting for each of the options listed above to let admins disable the feature globally and completely. The default of these settings should be "Enabled" to retain the current functionality of the plugin.
2. Add a capability for each of the options to let admins control who is allowed to use a feature and who is not. The capabilities should be assigned by default to the "Authenticated user" role to retain the current functionality of the plugin.

**Comment by dmitriim** [comment]
Pull request for this feature https://github.com/markn86/moodle-mod_customcert/pull/217
