### ISSUE TITLE
No option to edit existing template

### ISSUE THREAD

**Issue by JosiahCarberry** [markn86/moodle-mod_customcert#18]
At  Site administration / ► Plugins / ► Activity modules / ► Custom certificate / ► Manage templates / ► Edit custom certificate, there is an option to load a different template and an option to add a page to an existing template. But there is no option to modify an existing page for an existing template. Here is a screenshot showing the entire form:
![capture1](https://cloud.githubusercontent.com/assets/13927067/16461759/7673c65a-3e2e-11e6-8f04-14e2fc1749d0.png)

**Comment by markn86** [comment]
Wow, seems very broken! I don't know why 'Name' is the only field showing in that form. I created a new template and also edited an existing one and could not replicate the problem. Can you provide step-by-step instructions? Thanks.

**Comment by JosiahCarberry** [comment]
Following a complete reinstall, this issue has disappeared.
