### ISSUE TITLE
Allow users to load a global template but do not allow them to create their own template within the activity

### ISSUE THREAD

**Issue by abias** [markn86/moodle-mod_customcert#181]
We have the use case that users should only be allowed to load a global template but not to create an own template within the activity.

Similar to #137, I propose to add a new capability which allows users to create a custom certificate in the activity.

**Comment by abias** [comment]
On request by @dmitriim, I am adding some background information to this issue:
* Currently, as admin, I can create global templates which users can load in their activity instances.
* Currently, mod/customcert:manage controls multiple aspects of this activity plugin, including the fact that a user can load existing global templates into their activity instances and create own templates within their activity instances.
* As admin, I want to specifically control which users are able to create an own template within an activity instance and I can't do this yet as mod/customcert:manage is some kind of multi-purpose capability.
* As admin, I want to to separate two possible kinds of users:
1. A user wo can load a global template within an activity instance and who can also create his own template within the activity instance. The user will be able to create his own certificates besides the global templates which have been provided by the admin.
2. A user wo can load a global template within an activity instance but who cannot create his own template within the activity instance. The user will only be able to create certificates based on global templates which have been provided by the admin.
* The fact that a user can / cannot modify a loaded template within an activity instance is not covered by this issue. This is handled in #137.

**Comment by dmitriim** [comment]
Hi Alex, 
Sorry, but I'm confused by "users are able to create an own template within an activity instance". Is it possible at all? I can't see this in UI. Am I blind? :)

**Comment by abias** [comment]
Hi Dmitrii,

> Sorry, but I'm confused by "users are able to create an own template within an activity instance". Is it possible at all? I can't see this in UI. Am I blind? :)

I might have phrased this in a mistakable way. What I meant is:
* Login as teacher, go to your course and add an activity instance
* Open the gear icon (in theme_boost) -> Edit certificate
* There, you can load a global template. And you can simply create your own certificate by simply adding elements to your certificate. The second feature is what I meant with "create an own template within an activity instance".

It is clear now?

**Comment by abias** [comment]
This issue is superseded by #227 and will thus be closed.
