### ISSUE TITLE
New Fonts

### ISSUE THREAD

**Issue by oursteve** [markn86/moodle-mod_customcert#188]
Different certificates require different fonts to make them stand out, could new fonts be added esprcially Lucida Calligraphy.
Regards
Steve

**Comment by markn86** [comment]
Hey Steve,

The fonts are chosen from the fonts shipped in Moodle (see lib/tcpdf/fonts). If you want to add more fonts please add them there as I won't be shipping fonts with the plugin.

Cheers.
