### ISSUE TITLE
Unable to set background image

### ISSUE THREAD

**Issue by tluger** [markn86/moodle-mod_customcert#19]
I was told in a Moodle forum there isn't any way to set a background image. The activity developer wrote, "the best solution I can think of is to use an image, but that isn't ideal if all you want is to change the colour. The best solution would be to create another 'background' element that you can choose to add to the certificate (or maybe not an element at all but a setting for the certificate). I need to think about this."

I tried placing a transparent image with no background in the editor. It looked like it was going to work in the browser (see screenshot), but it did not display correctly in the downloaded PDF (also attached).

![screen shot 2016-06-29 at 11 15 04 am](https://cloud.githubusercontent.com/assets/17954687/16490824/2685e3a0-3e90-11e6-8242-31c09a6b58f9.png)

[Certificate_of_Participation-38.pdf](https://github.com/markn86/moodle-mod_customcert/files/341596/Certificate_of_Participation-38.pdf)

I have been working in Firefox on a Mac and viewing the downloaded PDFs in Preview on a Mac. I will also be creating a separate issue about the PDF not displaying correctly in Adobe Reader under any circumstance.

**Comment by JosiahCarberry** [comment]
I have found that a watermark type image that is behind other elements only requires that the watermark be higher in the list of elements than those that are layered on top of it.

**Comment by tluger** [comment]
Thank you Josiah! Your suggestion worked. I guess the order of the list kind of functions like layers.

Todd
