### ISSUE TITLE
Feature Request: Validation QR Code

### ISSUE THREAD

**Issue by michael-milette** [markn86/moodle-mod_customcert#194]
Would it be possible to add a new element which would add a QR code containing a URL to validate a certificate?

Best regards,

Michael

**Comment by markn86** [comment]
This idea came up again during our HQ dev meeting actually, where this was suggested. It's a good idea and something I will work on when given enough time.

**Comment by michael-milette** [comment]
Hi Mark,

That is great news! Looking forward to it.

Best regards,

Michael

**Comment by markn86** [comment]
Is this the same as #146?

**Comment by michael-milette** [comment]
It is indeed. Forgot that I asked for it back then. Guess the need never went away Don't worry though, it only needs to implemented once ;-)

Thanks,

Michael

**Comment by markn86** [comment]
Thanks Michael! It's high up on my to-do list for this plugin.
