### ISSUE TITLE
Build 2018051701 displays many elements in the wrong place

### ISSUE THREAD

**Issue by JosiahCarberry** [markn86/moodle-mod_customcert#196]
After installing build 2018051701 I note that some, but not all, elements are displayed in different places, generally set much too far to the left. Checking the positioning of the elements, I note that they have not changed. It is just how they are displayed in the pdf output.
I attach before and after images.
![before](https://user-images.githubusercontent.com/13927067/41094254-f310bdb0-6a4d-11e8-9a1a-345b609f5dd3.png)

![after](https://user-images.githubusercontent.com/13927067/41094253-f2a2ebc8-6a4d-11e8-8d5d-1476be5a0cd9.png)

**Comment by markn86** [comment]
Grr. This may be because of #170. Investigating ..

**Comment by markn86** [comment]
Can you tell me what those element types are that moved to the left? Are they all 'text' elements?

**Comment by markn86** [comment]
Are you also able to tell me what version you upgraded from?

**Comment by markn86** [comment]
Ah, I was able to replicate this. Thanks, working on fix now ..

**Comment by markn86** [comment]
Created fix. Thanks a lot for the report! Will be updating version on plugins DB soon.

**Comment by JosiahCarberry** [comment]
It might be moot now, but I upgraded from Build: 2017111301

**Comment by markn86** [comment]
New version is available on the plugins DB now. :) Again, thanks for the report so quickly.

**Comment by JosiahCarberry** [comment]
Fixed now. Thank you!
