### ISSUE TITLE
My Certificates and Verify Certificate pages not processed through Moodle filters

### ISSUE THREAD

**Issue by michael-milette** [markn86/moodle-mod_customcert#197]
Course name and Certificate name are not processed through Moodle filters on the **My Certificates** page, both in the listing and when you download the table data page, and the **Verify Certificate** page when a code is found to be valid. As a result, multi-language course names and certificates are not displayed correctly.

Note: Pull request coming shortly to correct these issues.

**Comment by michael-milette** [comment]
See Pull Request #198 .

**Comment by markn86** [comment]
Created a fix. Will be available next release. :)

**Comment by michael-milette** [comment]
Thanks you Mark! 👍
