### ISSUE TITLE
Use course module context when calling format_string/text()

### ISSUE THREAD

**Issue by markn86** [markn86/moodle-mod_customcert#200]
Filters can be applied at the course module context, so format_string/text should be using that context, not course.

List of elements this affects -

1. Category name.
2. Course name.
3. Grade item name.
4. Text.
5. User field.

**Comment by markn86** [comment]
Minor regression from #170. Most people won't have filters set up per course module basis.

**Comment by markn86** [comment]
Done!

**Comment by ewallah** [comment]
A weird thing happens during phpunit testing: with moodle-plugin-ci all tests pass (in travis.org AND local), but when I run all tests using "php admin/tool/phpunit/cli/util.php --run", 3 tests fail (line 247 - 310 - 372 of tests/element_helper_test.php) - failed asserting that two strings are equal '50.000 %' vs '50.00 %'

**Comment by markn86** [comment]
Bah, sometimes I hate software development, why can't it just play nice.

Wondering if it's worth creating an issue for ..
