### ISSUE TITLE
Missing local_mobile service

### ISSUE THREAD

**Issue by jleyva** [markn86/moodle-mod_customcert#202]
Hi Mark, you should add the 'local_mobile' service among the official one so it works in sites pre 3.5 using local_mobile:
https://github.com/markn86/moodle-mod_customcert/blob/2868082e9e3f5c81e0bd741e778dfc16db37fcb8/db/services.php#L35

See:
https://github.com/markn86/moodle-mod_certificate/blob/MOODLE_31_STABLE/db/services.php#L35

**Comment by markn86** [comment]
Thanks Juan! Will be available next release. :)
