### ISSUE TITLE
Background image element not showing on custom certificate (Moodle 3.1)

### ISSUE THREAD

**Issue by FPVLearning** [markn86/moodle-mod_customcert#204]
Hi,

After adding all the relevant elements, when I go to preview/issue a certificate, the background image does not appear. It is a custom border saved as a jpg.

Thanks

**Comment by markn86** [comment]
Hi,

Thanks for the report.

Would it be possible to get a copy of the image you are using?

**Comment by FPVLearning** [comment]
No problem. Here it is:

![certificate border1](https://user-images.githubusercontent.com/40254109/41389471-68cf0aa8-6fd4-11e8-9cb0-f41a221fe246.jpg)

Thanks
Hayley

**Comment by markn86** [comment]
Hi Hayley,

This works for me.

Just a note - the background image element is not very intuitive (I should really improve it). Once you upload the image you will have to re-editing the element and select the element from the drop-down.
