### ISSUE TITLE
Role with permission to view all certificate cannot see certificate

### ISSUE THREAD

**Issue by emmarichardson** [markn86/moodle-mod_customcert#206]
I have a trainer role that cannot access all groups but is given permission to see things for students in their group.  I have given them the role to view all certificates but if they click on a certificate for a student, they get a permission not allowed error.

**Comment by markn86** [comment]
Hi Emma, any update on this or can I close it?

**Comment by emmarichardson** [comment]
Sorry Mark. I will check on this in the morning and report back.
On Dec 17, 2018 8:42 PM, "Mark Nelson" <notifications@github.com> wrote:

Hi Emma, any update on this or can I close it?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/markn86/moodle-mod_customcert/issues/206#issuecomment-448085922>,
or mute the thread
