### ISSUE TITLE
Rename and reformat "rearrange elements"

### ISSUE THREAD

**Issue by JosiahCarberry** [markn86/moodle-mod_customcert#21]
I suggest that "rearrange elements" be renamed to "Re-position elements" and that it be put in a button, as is "add another certificate page". This would be much clearer, IMHO.

**Comment by markn86** [comment]
I changed the text but left the location. It is a link, not a button so for accessibility reasons will leave it that way. 

Note: I also found an issue where an extra column was being added to the table unnecessarily and removed this so hopefully that also makes it clearer.
