### ISSUE TITLE
Date format with leading zeros

### ISSUE THREAD

**Issue by anieminen** [markn86/moodle-mod_customcert#210]
Hi,

I have a problem with date format in the certificate **date** element. There are 2 short date formats to select from, but the day number in those is always shown without leading zeros. In month numbers there are leading zeros: 

![image](https://user-images.githubusercontent.com/15781654/42325663-8c77757a-806f-11e8-80b8-314136c65b92.png)

In Finland we use date formats like _5.7.2018_ or _05.07.2018_ , but neither of them is possible with current settings. 

I tried editing Moodle language file (langconfig.php), but this behavior cannot be changed, although format `%d` in PHP function `strftime()` should be "Two-digit day of the month (with leading zeros)". 

I did some digging and the reason for this seems to be `userdate()` function in Moodle core, which [strips leading zeros from `%d` format by default](https://github.com/moodle/moodle/blob/master/lib/moodlelib.php#L2216) .

So a fourth parameter `false` should be added to `userdate()` function call when using those short date formats `strftimedatefullshort` and `strftimedatetimeshort`. Can this be fixed?

**Comment by anieminen** [comment]
Great, thanks!

**Comment by markn86** [comment]
Done!

**Comment by Markibacsi** [comment]
@anieminen 
We also use the date format 18.07.2018 in Romania. Did you manage to achieve this format, as opposed to 18/07/2018?

I too tried to edit the langconfig.php file, but there are no changes reflected on the user end??

**Comment by Markibacsi** [comment]
@anieminen 
Just tried again - and editing the strftimedatefullshort string (langconfig.php) from %d/%m/%y to %d.%m.%Y (replacing the '/' with '.', and capital 'Y') gives the desired result :)
