### ISSUE TITLE
Fonts files path should not be hard-coded

### ISSUE THREAD

**Issue by TomaszGasior** [markn86/moodle-mod_customcert#211]
Please see this file: https://github.com/moodle/moodle/blob/master/lib/tcpdf/fonts/readme_moodle.txt It states that it's possible to override preinstalled fonts with custom fonts inside `$CFG->dataroot/fonts`.

But it's impossible to use custom fonts from `$CFG->dataroot/fonts` because in this addon fonts files path is hard-coded and can't be overwritten easily. It's here: https://github.com/markn86/moodle-mod_customcert/blob/MOODLE_35_STABLE/classes/certificate.php#L102

To fix problem, please use path defined here: https://github.com/moodle/moodle/blob/master/lib/pdflib.php#L87

**Comment by markn86** [comment]
Thanks for the report. Will create a fix shortly.

**Comment by markn86** [comment]
This function really should be using -

```
$pdf = new \pdf();
$fonts = $pdf->get_font_families();
```

**Comment by markn86** [comment]
I have updated the docs https://docs.moodle.org/35/en/Add_fonts_for_embedding (for 3.4 and 3.3 as well). Working on a fix now.

**Comment by markn86** [comment]
Created fix, thanks for the report.
