### ISSUE TITLE
Upload image to certificate problem 

### ISSUE THREAD

**Issue by iFnno** [markn86/moodle-mod_customcert#212]
Hello all,

First of all, I would thank you for this amazing plugin.
I just faced a problem when uploading an image here 
![upload](https://user-images.githubusercontent.com/32503927/42490893-25ca8e0c-841b-11e8-88c2-86498e8e254d.PNG) it doesn't appear on image dropdown menu here 
![image](https://user-images.githubusercontent.com/32503927/42490915-4375b6b6-841b-11e8-9aac-a728f112525b.png) until I save the changes and getting back to the same page again it will appear on the drop-down. Is there any way to make the image shown on the drop-down menu without saving the changes?

Thank you again.

**Comment by markn86** [comment]
Thanks.

This bugs me as well.

Solution requires some JS and unfortunately there is no available API in Moodle (that I am aware of) I can use.

One problem to consider is that the image is not 'saved' until you submit the form. When you upload it to the filepicker it is only in the draft file area (think of it as a temporary file area in Moodle). If you were to cancel the form then it would not be shown if you were to re-edit the element. We need to ensure the select box value is only saved if the file is successfully uploaded.

**Comment by markn86** [comment]
The also happens in other areas of Moodle. For example, when uploading a profile picture (well it did, haven't checked recently).

**Comment by iFnno** [comment]
@markn86 Thank you

**Comment by markn86** [comment]
Ok, so there are far more important issues I need to address that keep piling up. There isn't enough time. I am going to clean the backlog, so closing this.
