### ISSUE TITLE
Feature Request: Add content of the previous form, field Description

### ISSUE THREAD

**Issue by clydde** [markn86/moodle-mod_customcert#215]
It would be useful for use with templates.

table > **customcert > intro** field

**Comment by markn86** [comment]
Do you mean add an element you can add to the certificate that will display the intro on the PDF?

**Comment by clydde** [comment]
This would allow to create different templates and to put the variable text of each certificate at the moment of creating it.

**Comment by clydde** [comment]
Waiting for response?

**Comment by markn86** [comment]
Thanks for the explanation @clydde. Sorry for the delay in responding. I am extremely busy working on Moodle 3.6 and have had no time to dedicate to this plugin. However, once 3.6 release comes out and things calm down I will find a whole week to triage all these issues and release a new version.

**Comment by markn86** [comment]
This will be a difficult one to address and I really don't think it's valid. The PDF will only support text, yet in the description you can add media which won't translate well. I could come up with a hack to strip out all the media content but then there will be leftover tags etc. It would get messy.

**Comment by markn86** [comment]
I am deciding to close this as it would be too time consuming for me to find a way to do this in a sensible fashion given the above comment. Eg. what do we do if someone adds a recording, or attaches a video?
