### ISSUE TITLE
Allow Automatic Certificate Issue Following Activity (ie. Exam completion)

### ISSUE THREAD

**Issue by scottb505** [markn86/moodle-mod_customcert#219]
Good evening, I was wondering if there is any way to have the certificate automatically issue/create itself after completing an activity (such as an exam) and achieving the pass mark. Currently run into the issue where certain students either forget or do not issue their own certificates, and having it automatic would make the process seamless and remove this problem completely (if it is possible).

**Comment by Markibacsi** [comment]
@scottb505 

You can use the 'Restrict access' settings for the Custom Certificate activity.
I use a quiz activity as a course ending test, where the students must achieve a grade of 60%. Once the grade is achieved, the certificate is generated. (Edit settings > Restrict access > Add restriction > Grade)

We also get the system to email the certificates to the students at the time of issue. (Edit settings > Options > Email students)

**Comment by markn86** [comment]
Thanks Mark for your answer. I am closing.

Note - make sure your site cron is running in order for the certificates to be emailed.
