### ISSUE TITLE
Background Image SVG

### ISSUE THREAD

**Issue by thejnorky** [markn86/moodle-mod_customcert#228]
I have been playing with the .svg file format and it looks perfect in "reposition elements" but when i preview it as a PDF, the image is warped.

![certificate](https://user-images.githubusercontent.com/42581785/44413296-aaf50e00-a530-11e8-82b0-1e8be2ded10c.jpg)

**Comment by markn86** [comment]
Hm, this might be an issue with the TCPDF library itself as that is responsible for the generation of the PDF (I did not write that library). I will have to try myself with a .svg. Can you confirm if it happens with all of them?

**Comment by thejnorky** [comment]
I was able to get the problem resolved with trying different variations of a SVG file.

**Comment by markn86** [comment]
Thanks for the response.
