### ISSUE TITLE
Completion date not displayed for certificate after Cron run

### ISSUE THREAD

**Issue by Rabecerra** [markn86/moodle-mod_customcert#232]
Hi Customcert team,

I've been following this issue https://github.com/markn86/moodle-mod_customcert/issues/113 and it's solution in https://github.com/markn86/moodle-mod_customcert/commit/48bb4e23b972505dc088b95ed92a403fec844c39, I did this https://github.com/markn86/moodle-mod_customcert/issues/118#issuecomment-320854599, to replicate and try to see the completion date, but not luck. I think this could be broke again, since the changes in https://github.com/markn86/moodle-mod_customcert/issues/118#issuecomment-320854599 were reverted because https://github.com/markn86/moodle-mod_customcert/issues/98, I was wondering for a solution on this case. 

Can someone double check if this bug is indeed happening.

Thanks a lot for your help!

**Comment by markn86** [comment]
The completion date is still working as expected, please ensure you have the cron run (it has to run twice).
I couldn't follow the logic in what you wrote because I never reverted any code.
Closing since no one else has complained this isn't working as expected and I just tested it successfully.
Cheers.

**Comment by dsmith23** [comment]
I'm also having problems with using the completion date but not sure it is the Custom Certificate fault. So far on one test, it does not work. I get a current date instead which I think is a date the site was recently updated. Can you tell me where the date the test (Topic: Test 1) is taken is pulled from? I've looked in the database and so far the stamp dates that I have looked at are correct.  Thanks for any help.

**Comment by JozefKuco** [comment]
I have similar problem. 
Example:
I have set up date to be pulled from Topic: 0 -> i have completed acitivty through administration (activity completion) -> now students dont have dates on certificates. 

Anyone to help mi with this issue? It is still bugged, or it is only some setings, that needs to be solved.
Thanks!

P.S. plugin is great!
