### ISSUE TITLE
field "element" in customcert_elements is LONGTEXT

### ISSUE THREAD

**Issue by gabriosecco** [markn86/moodle-mod_customcert#241]
the field "element" in the customcert_elements table is set to longtext instead varchar, but actually its content should be a very short text (sub-plugin name).
A side effect is I can't write code like this
$DB->get_records("customcert_elements", array('pageid' => $pid, 'element' => 'mycustomelement')
because it doesn't work with longtext fields

**Comment by markn86** [comment]
Done! Thanks for the report.
