### ISSUE TITLE
letter (hybrid) scale - numbers don't appear in the certificate

### ISSUE THREAD

**Issue by Filippo73** [markn86/moodle-mod_customcert#242]
Hi, I'm using last release of Moodle (3.5.2+) and of Custom Certtificate (3.5.4).
I created a new course with a quiz inside and a letter (hybrid) scale (i.e. A1, A2... C1, typical for language evaluation).
Everything works fine but even if in the Grade field I choose Letter format the numeric part of the level doesn't appear in the certificate.
For example if a student finishes the quiz with a B2 level the certificate shows only the letter B and not the number 2 (that's fundamental in the Common European Framework of Reference for Languages).

**Comment by markn86** [comment]
Hi @Filippo73,

Can you please provide exact replication steps so I can work on this issue.

Steps like -

# Log in as admin.
# Create a course.

I may be a Moodle developer but do not use it as a teacher myself, so am not sure what a letter (hybrid) scale is. Clear steps to replicate it would really be appreciated.

**Comment by Filippo73** [comment]
Hi @markn86 ,
I try to do describe what I did:

- Log in as admin.
- Create a course.
- Create a Quiz inside the Course.
- Click on 'Grades'
- Choose "Scale"
- Create a New Scale with values "A1, A2, B1, B2, C1, C2"
- Force the system to use this scale with the course/quiz I created
- I set the range of points a students should gain in the quiz to reach level A1, A2, and so on...
- At the end in the grades section I see the correct results, witht the values I created
- I create a new certificate for the course
- Choose Letter as the Grade format
- The certificate show me only the alphabetic part of the scale and not the numeric, i.e. it stamps A instead of A1

I hope it can help You.
Best regards.

**Comment by markn86** [comment]
Thank you.

I was able to replicate this. Seems it's completely broken actually. It was printing completely wrong value when I tried it. Will fix today.

**Comment by markn86** [comment]
Created a fix, thanks for reporting this! This will be in the next release.

**Comment by markn86** [comment]
Ok, I was confusing myself between GRADE_DISPLAY_TYPE_XYZ and GRADE_TYPE_XYZ.

I fixed an issue where we were assuming the grade type was GRADE_TYPE_VALUE, when it can actually be scale. So, now I use the grade_item object to determine that, rather than setting it to that.

The 'Grade format' option can remain in the form as that is just related to how it is displayed. So, for scales you should use 'Points'.
