### ISSUE TITLE
HTTP Error 500 on previewing the certificate

### ISSUE THREAD

**Issue by ketanchhaniyara** [markn86/moodle-mod_customcert#244]
Hi,

I am using Moodle 3.5 and plugin version is 3.5.4. It was working properly, I created the perfect template and saved it. But suddenly it started giving HTTP Error 500 on previewing the certificate. It works perfectly in repositioning the elements, just previewing gives this error. No changes are made to the server or moodle. Don't know how it got stopped suddenly.

I also reinstalled the plugin but still the problem persists.

![screenshot 1](https://user-images.githubusercontent.com/44313996/47253279-7dfca300-d46e-11e8-88d6-c3b1e90fea56.png)
![screenshot 2](https://user-images.githubusercontent.com/44313996/47253280-7dfca300-d46e-11e8-983d-db0afe2a7931.png)

**Comment by markn86** [comment]
Since I can't replicate it and no one else has reported this it sounds to me like a permission issue for files/folders in your server directory.

**Comment by ketanchhaniyara** [comment]
> Since I can't replicate it and no one else has reported this it sounds to me like a permission issue for files/folders in your server directory.

Thank you so much for your response.
I am a novice, can you please guide me which files/folders require permissions? I have given full rights to everyone to Moodle directory.

**Comment by markn86** [comment]
Please take a look at https://docs.moodle.org/36/en/Security_recommendations#Most_secure.2Fparanoid_file_permissions.

**Comment by markn86** [comment]
Also https://www.webhostinghub.com/help/learn/website/website-help/500-internal-server-error.

I am closing this issue now since it is not something I can fix.
