### ISSUE TITLE
A certificate already exists with this name

### ISSUE THREAD

**Issue by tluger** [markn86/moodle-mod_customcert#25]
Hi

I created a certificate in a test course and gave it a specific name in the edit custom certificate interface. I then deleted the course and all its activities. I then created 15 courses from a template using a course upload file and began the process of renaming the certs in each one. However, the system would not allow me to reuse the cert name from the deleted course. I got an error that said it already exists. It must just exist in a database, because the name is not being used in any other custom cert activity. I am not able to locate an admin panel that would allow me to remove cert names associated with deleted custom cert activities. 

Is there any way to do this. I do have access to the databases if need be. 

Thanks. 

Todd

**Comment by markn86** [comment]
Looking into this now.

**Comment by markn86** [comment]
Hi Todd, are you able to confirm that a template is not using the same name via <yoursite>/mod/customcert/manage_templates.php?

**Comment by markn86** [comment]
Closing as I believe it's related to https://github.com/markn86/moodle-mod_customcert/issues/49.
