### ISSUE TITLE
HTML tags in columns when download report

### ISSUE THREAD

**Issue by jmendozapuche** [markn86/moodle-mod_customcert#253]
Hi, I'm having problems when exporting a report in Excel or CSV format. Seems like HTML is not converted and then tags appear in file, avoiding correct visualization.

The rest of functionalities are working properly.

Please your help!

![reportissue](https://user-images.githubusercontent.com/45106659/48640569-0c4c4200-e9a5-11e8-8c9b-01ee154767aa.JPG)

**Comment by jmendozapuche** [comment]
Thanks for answer and for your plugin Mark, I'm using version 2016120516 in Moodle 3.2.8+. If there is possibility to update without data lost please let me know to follow instructions.

**Comment by markn86** [comment]
Hmm, I did not seem to release a new version of the plugin when I introduced that patch and I no longer support Moodle 3.2. To see the changes please see https://github.com/markn86/moodle-mod_customcert/commit/6c21cd41cbea380cbe59357692bb580f925785f5 which you can apply manually.
