### ISSUE TITLE
Text with same name as activity becomes an unaligned link

### ISSUE THREAD

**Issue by paulisfluent** [markn86/moodle-mod_customcert#257]
After an upgrade from Moodle 3.2.4+ (customcert 3.2.14) to Moodle 3.5.3 (customcert 3.5.4), I noticed a change in behaviour for our custom certificate.

Where some text used to be black and centred, it is now a blue underlined link (URL to its own customcert activity on the Moodle site) and aligned to the left:

![image](https://user-images.githubusercontent.com/18393158/49933959-03c42a00-fec5-11e8-8aa3-b2173411f427.png)

When I changed the text, it went back to normal:

![image](https://user-images.githubusercontent.com/18393158/49934001-1d657180-fec5-11e8-9eed-843d5d4af7b3.png)

When I changed the name of the activity to the same as the new text, the problem returned:

![image](https://user-images.githubusercontent.com/18393158/49934266-c6ac6780-fec5-11e8-85ea-6161035b0598.png)

It looks like there is some magic that formats text as a link if it matches the activity name.  I don't know if this was deliberate, but it was certainly surprising behaviour to me!

I am a programmer, but haven't dug into the changes of this code enough to find exactly where this happens yet.  Let me know if you'd like me to try anything else, or if there's any other information you need.

**Comment by markn86** [comment]
Hi Fluent Paul,

Thanks for the report.

I can almost guarantee this is because of #170.

You can deactivate the filter 'Activity names auto-linking' by visiting 'Site administration' > 'Plugins' > 'Filters' > 'Manage filters' (or ask your admin to do so if you can't). If you require the use of this filter then the title will have to be different than the activity name.

HTH,

Mark

**Comment by paulisfluent** [comment]
Great, thanks Mark.

I can confirm that turning off "Activity names auto-linking" put the text in its proper place again.  (I didn't know about this option or I might have looked there already!)
