### ISSUE TITLE
Setting email to students to yes causes all enrolled students to be issued a certificate

### ISSUE THREAD

**Issue by emmarichardson** [markn86/moodle-mod_customcert#259]
I added the certificate activity to an existing course that had 5 students enrolled.  I set the activity to email to students.  I noticed that when I went into the certificate activity, it had issued all enrolled users a certificate automatically.     Is this by design?  If this is set and there are restrictions, will it automatically email a student that completes the requirements to access the certificate?

**Comment by markn86** [comment]
Hi Emma,

Yes, currently it will automatically email any student in the course who has not already received a certificate issue and are eligible for one. When setting up the certificate make sure to include any restrictions before a user can access it, or only turn on the email students flag when you are ready.

HTH,

Mark

**Comment by emmarichardson** [comment]
Thanks Mark. But, after that had been enabled, that doesn't happen when
they complete the prerequisite activities? They have to go to the
certificate and click on it before it will email? Or does it automatically
issue? That would be useful!

**Comment by markn86** [comment]
There is a task that runs when Moodle cron runs (automatic) that checks if there are any certificates that want to email their users, if there are it then checks if there are any users that haven't been issued the certificate and then checks if the user can access the activity or not. If they can, then it will email them. It is all done automatically.
