### ISSUE TITLE
Module doesn't respect Activity Auto-linking filter off setting

### ISSUE THREAD

**Issue by tbahula** [markn86/moodle-mod_customcert#265]
I noticed a problem with one of our certificate layouts after upgrading to Moodle 3.5.3+ (20181120) with Custom Certificate version 2018051704.

The name of the certificate, Certificate of Completion in Russian, was auto-linked to the activity with the same name. I tried changing the filter setting for activity auto-linking to off for the Custom Certificate; however, that didn't change anything. The certificate only rendered properly when I turned activity auto-linking off for the whole course.
![image](https://user-images.githubusercontent.com/14959510/52159738-8754f880-2676-11e9-92d5-2cf9a3445336.png)
![image](https://user-images.githubusercontent.com/14959510/52159750-b7040080-2676-11e9-87b5-f44780eec4b7.png)
![image](https://user-images.githubusercontent.com/14959510/52159755-d307a200-2676-11e9-9e47-5a55ab563db1.png)

I notice that another user mentioned this problem on the Issue #222 thread. The resolution was to disable activity auto-linking for the course. That isn't an option for us. The course uses extensive linking between activities.

**Comment by tbahula** [comment]
For what it's worth, it is relatively easy to fool the activity auto-linking filter by replacing one of the spaces in the title with &nbsp;

**Comment by markn86** [comment]
This should be fixed by #200 as it now uses the module context. :)
