### ISSUE TITLE
State number of certificates awarded

### ISSUE THREAD

**Issue by wildgirl** [markn86/moodle-mod_customcert#266]
It would be great for courses with a large number of participants such as Learn Moodle Basics to state the number of certificates awarded. 

How about under the heading 'Recipients' having a sentence 'Number of certificates awarded: xx'?

**Comment by markn86** [comment]
Done. Will release new versions shortly when I get time with this included.

**Comment by wildgirl** [comment]
Thanks Mark, we'll appreciate this issue fix on https://learn.moodle.net/ :-)
