### ISSUE TITLE
E-mail with certificate sent in English - No translated to spanish

### ISSUE THREAD

**Issue by lapega** [markn86/moodle-mod_customcert#267]
I've Moodle 3.6 configured in spanish, but the e-mail sent to student is in English.

> Hola
>
>Attached is the certificate 'Certificado de asistencia' for 'UNIT ISO' for the
>course 'Gestión de la Calidad y Sistemas Integrados'.

Do I need to enter a new translation string for this?

**Comment by markn86** [comment]
Yes, a translation is required. This can be done at https://lang.moodle.org/. :) The language translations are kept there and updated by the community, rather than waiting for the plugin developer. Thanks!
