### ISSUE TITLE
Old Certificate Plugin: Course reset/timeshift bug.

### ISSUE THREAD

**Issue by jjs105** [markn86/moodle-mod_customcert#272]
Firstly apologies if this is the wrong pace to report a bug with the old certificate plugin (both plugins share a forum and issues are turned off for the other Git repo) but the moodle page does specify that bug fixes are still being applied, ...

When resetting a course in moodle the certificate_reset_userdata function (lib.php) is called which, if the course reset includes a 'timeshift', tries to apply date operations to non-existent database columns 'timeopen' and 'timeclose' (lines 132-135).

This in turn causes an unrecoverable error that breaks the reset operation.

To reproduce:

1. Create a course ensuring that a non-midnight start date is specified
2. Add a certificate to the course
3. Reset the course setting a new start date, but keeping the same non-midnight time

The solution to the issue is to either a) remove the 'timeshift' code if it is not needed or b) update the code to only modify appropriate database columns.

This error seems to have originated from the original creation of the plugin being based on an activity which does have the 'timeopen' and 'timeopen' database columns.

As an aside this issue is not present in the update custom certificate plugin.

**Comment by markn86** [comment]
Hi, yes, this should be posted in https://github.com/markn86/moodle-mod_certificate. If you provide a a code patch i'll happily integrate it.

**Comment by jjs105** [comment]
Hi, I will create a pull request, however I posted here because, as stated, issues cannot be created in the repo as you suggest.

**Comment by markn86** [comment]
Thanks for letting me know. I have added the ability to create issues on that repository.
