### ISSUE TITLE
Unit test fails in MOODLE 34

### ISSUE THREAD

**Issue by yao9394** [markn86/moodle-mod_customcert#277]
1) mod_customcert_element_helper_testcase::test_get_mod_grade_info
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'50.000 %'
+'50.00 %'

/var/www/site/mod/customcert/tests/element_helper_test.php:247
/var/www/site/lib/phpunit/classes/advanced_testcase.php:80

To re-run:
 vendor/bin/phpunit "mod_customcert_element_helper_testcase" mod/customcert/tests/element_helper_test.php

Hi trying to install this plugin on Moodle 34, but got this error. Can anyone please look at this?

**Comment by markn86** [comment]
This passes for me.

**Comment by markn86** [comment]
This is odd because unit tests should pass regardless of what machine they are run on. I am guessing `$grade_item->get_decimals();` is returning a different value than a standard install. Do you have a setting on config.php to set this?

**Comment by markn86** [comment]
This I solved this, will backport later.

**Comment by yao9394** [comment]
Hi @markn86 

Thank you for fixing this. Could you please fix this on MOODLE_34_STABLE branch? 

Thank you

@yao9394

**Comment by markn86** [comment]
I'll backport once I perform another release.

**Comment by yao9394** [comment]
Thank you very much @markn86

**Comment by yao9394** [comment]
Hey @markn86 ,

Just following up the progress of backporting to MOODLE34. When can we expect the patch updated on the branch?

Thank you

**Comment by markn86** [comment]
3.4 is now unsupported for both bug fixes and security (see https://docs.moodle.org/dev/Releases) so I suggest upgrading or cherry-picking the fix to your install. Thanks!
