### ISSUE TITLE
Loading a template with no matching data requires additional work

### ISSUE THREAD

**Issue by markn86** [markn86/moodle-mod_customcert#28]
If a template does not have a teacher selected (due to it being in the system context) it causes an issue when loaded into a course as the field isn't populated. It required editing the field and saving it again so that the teacher field is populated.

**Comment by Hammur20** [comment]
Hi, just want to inform that I've manage to get the teacher element populated for a template. This happened kinda by random though, not sure exactly how.

I was creating a template and was using Firebug to place the elements to their right place and I also had a teacher element. It was as usual empty with no teacher selected (and could not select one either). Now when the element width is set to 0 and no teacher selected, the field is hidden on the "Reposition elements" page including the reference point, making it impossible to position by dragging it. So to get it to show I added some random text in the element html using Firebug. It could then be seen and I placed it where it should be.

However when I clicked save, the teacher element received a actually name of a teacher-user in the system. I found this very weird, and don't really understand how this happened. But just adding some random text to the teacher element html using Firebug made it select a user (random I guess), which in our case was the site moderator who is also an actual teacher sometimes.

The teacher element does hereby for us have a user selected and when creating a new template adding a teacher field, we can now always have that user selected as teacher (He is the only option to select). Our templates does this way have this user selected as a default teacher and if the template is added to a course with a different teacher, we just change the teacher name there.

**Comment by markn86** [comment]
The site template has access to only the teachers in it's context. Now, for example, if you add a teacher on a site template the value saved in the DB will be the id of the teacher. When you then load this on a course it can't find the user id so nothing is displayed. If you were to then edit the teacher element for that certificate and save it it would fix this issue as the select box would be generated with the list of teachers in that course and then when saving it would just save it as the first one in the list. I suspect on the repositioning page by changing the value it is not ignored during save anymore and rectifies itself.

**Comment by markn86** [comment]
The same happens for grade and date.
