### ISSUE TITLE
Add Permissionable hiding of Item in Profile

### ISSUE THREAD

**Issue by dustinbrisebois** [markn86/moodle-mod_customcert#285]
Greetings

As per: https://github.com/markn86/moodle-mod_customcert/blob/b211a06bd50559c3e6c1a6d36600307084fa6e5b/lib.php#L370

I am wondering if we can add a permission to hide the "My certificates" item from the user profile list shown here:

![image](https://user-images.githubusercontent.com/16727280/58190660-dcdb0280-7c71-11e9-9500-c8ff3658f4c9.png)

If something like:

`function mod_customcert_myprofile_navigation(core_user\output\myprofile\tree $tree, $user, $iscurrentuser, $course) {
    if (has_capability('mod/customcert:viewallcertificates', $PAGE->cm->context)) {
        $url = new moodle_url('/mod/customcert/my_certificates.php', array('userid' => $user->id));
        $node = new core_user\output\myprofile\node('miscellaneous', 'mycustomcerts',
            get_string('mycertificates', 'customcert'), null, $url);
        $tree->add_node($node);
    }
}`

Instead this would ensure that the permission can remove the list of cerficates.

**Comment by markn86** [comment]
This can be done in CSS. See comment in PR.

**Comment by dustinbrisebois** [comment]
My apologies, I was under the impression that the "viewallcertificates" wasn't for ALL users just all the certificates for your user. 

Doing this in CSS is impractical, it needs to be done with JavaScript AND CSS - which is ugly, compllicated and unnecessary. As there are no proper tags within the box this isn't easy to target/remove from the DOM (as least in the LMS version that I'm using for this).

Is it possible to use the same code I provided but add a new permission that allows for removal from the navigation menu?
