### ISSUE TITLE
Don't store the fact that a certificate has been issued AND/OR add the current date as data source for the date element

### ISSUE THREAD

**Issue by abias** [markn86/moodle-mod_customcert#289]
Hi Mark,

we are using this plugin to generate a report for students which shows them which parts of the course they have already finished and which they have yet to do.
The goal of the certificate is that a student can download it anytime and that it always will show the current status of the course to him.

Our certificates especially have date and daterange elements added to them. Currently, these elements are configured to use the issued date as data source.

I have now seen that there is a difference between our expectation and they way which the plugin really behaves:

What the plugin does:
* As soon as a student downloads his certificate, this is recorded for future reference.
* As soon as a student downloads his certificate, the student sees a line saying "Awarded on: [...]" on the plugin main page.
* As soon as a student downloads his certificate, the teacher sees the student in the list of awarded certificates.
* If the student downloads the certificate again, the certificate shows the current status of the course
* If the student downloads the certificate again, the "Awarded on: [...]" line is not updated to the current date
* If the student downloads the certificate again, the list of awarded certificates is not updated to the current date
* If the student downloads the certificate again, date elements configured with "Issued date" as data source show the date when the certificate was awarded for the first time.

What we would expect it to do:
* When soon as a student downloads his certificate, he should not see a line saying "Awarded on: [...]" on the plugin main page as the certificate is not really "awarded".
* The teacher does not necessarily need to see the student in the list of awarded certificates.
* If the student downloads the certificate again, the date elements shows the date when the certificate was _downloaded_.

Against this background, I would propose two additions:
* Add a data source to the date and daterange elements which is filled with the current server date instead of the issued date
* Add a plugin instance option (including an admin default setting and a capability) which can be used to configure if the plugin records awarded certificates or not.
** If set to yes, the plugin behaves exactly as it does now.
** If set to no, 
*** the plugin does not record the date of the first download of a certificate
*** the plugin does not show the "Awarded on: [...]" line
*** the plugin does not show the list of awarded certificates to teachers
*** the date and daterange elements will fill the "Issued date" data source with the current server date

Do you think these additions are realistic?

Cheers,
Alex

**Comment by markn86** [comment]
As discussed we are simply going to add the ability to set the date to the current time, so there is no connection to the issued date.
