### ISSUE TITLE
Custom certificate does not appear on My Certificate page after successful quiz

### ISSUE THREAD

**Issue by klorinczi** [markn86/moodle-mod_customcert#291]
Using Moodle 3.5.1+ (Build: 20180810), mod_customcert v3.5.4 (2018051704)

Custom certificate does not appear on My Certificate page after a successful quiz.

It has a condition to do a specific quiz with 60% or more result, then the student gets the certificate. 
However after a successful quiz post, no new records are appearing on the My Certificate page or the mdl_customcert_issues table.

Anybody can answer why?
Is the certificate generation event based or it is collected by cron?

Thanks,
Konrad

**Comment by markn86** [comment]
The certificate has to be issued before it is shown on that page. For it to be issued the user can either manually download it, or when the cron runs and you have 'Email students' set to 'Yes' they should receive it there.

**Comment by klorinczi** [comment]
There is nowhere described, that if the 'Email students' set to 'No', then the issues will not appear for the users.

**Comment by klorinczi** [comment]
Mark, even if the 'Email students' set to 'Yes', I don't get email after I successfully filled the quiz, which is connected as condition to the custom certificate plugin.

What can be the reason? 
How can I debug it?

**Comment by markn86** [comment]
Is your cron running (see https://docs.moodle.org/37/en/Cron).
