### ISSUE TITLE
Arabic Letters are not supported in the dynamic fields

### ISSUE THREAD

**Issue by mohamedmohamedatia** [markn86/moodle-mod_customcert#293]
Most of the fonts in the certificate are not supporting Arabic letters in the certificate dynamic fields such as Names and Course Names. and all Arabic letters appear as question marks.

![image](https://user-images.githubusercontent.com/30835105/59762249-81675900-929f-11e9-9d73-2f04910ea6c3.png)

**Comment by markn86** [comment]
Unfortunately there is nothing I can do about this. This is dependent on the font you have chosen and if those characters are present.

See https://moodle.org/mod/forum/discuss.php?d=230356.

**Comment by mohamedmohamedatia** [comment]
I guess a solution is to allow admin to add custom fonts. then they can use from the list.
or adding a font such as Droid Arabic Kufi or Tahoma to the list. 

do you think this might be a fix ?

**Comment by markn86** [comment]
One of the fonts that ship with Moodle core should work. When you are adding the element there is a drop down, try another font. If you really need to you can add your own font (see https://docs.moodle.org/37/en/Add_fonts_for_embedding) but I have never done this before.

**Comment by abdulrehmanbinaltaf** [comment]
@mohamedmohamedatia try to use "Free Mono" or "Free Serif",  default font and Arabic /URDU will work.
Free Mono
![image](https://archive.org/download/free_mono/free_mono.jpg)
Free Serif
![image](https://archive.org/download/free_mono/free_sherif.jpg)
