### ISSUE TITLE
Add more date formats to date element

### ISSUE THREAD

**Issue by Hammur20** [markn86/moodle-mod_customcert#30]
Hi Mark. Thank you for this great plugin.

A suggestion for the date element, it would be nice to have some extra 'short-date' format to choose between with abbreviated and decimal month-name/number. 

Currently there are these available. (what is User date format?)
- February 1, 2000
- February 1st, 2000
- 1 February 2000
- February 2000
- User date format

Extra date format that would be useful to have are for example:
- 1 Feb 2000
- 01.02.2000
- 01/02/2000
- 01-02-2000

Also it would be nice to have an 'Expire' date item to the date element as well. Which would add a date xx days/weeks/years after course completion or issued.

Thanks in advance.

**Comment by markn86** [comment]
Thanks for the report. Will see if I can get round to this during this week. I plan on making a few improvements, though most are aimed at the reporting page.

**Comment by Hammur20** [comment]
That's great Mark. Looking forward to try out the new version.

I don't see an issue for an 'Expire' date item to the date element that I mentioned in the customcert forum. So thought I'd just add it to this issue, as it would be a very useful feature to have as well.

**Comment by Hammur20** [comment]
A nice thing, could make the expiry element similar to the Badge 'expiry field', where you can select Never, Fixed date, Relative date. Not sure if that was what you are planing?

**Comment by jorgensendaniel** [comment]
I need to be able to write the date on the certificate in danish... Right now, I'm only able to write the date in english.. Would it be possible to change that?

Thanks in advance

**Comment by frumbert** [comment]
I'd like to be able to specify the format myself (it's what I initially though "user date" was for) on a date element item.

You'd have a drop down item for "custom format" then reveal a field allowing the format to be specified. Then when get_date_format_string is doing its thing, it would allow for whatever date arrangement I'd chosen, e.g. 

    $certificatedate = userdate($date, '%a, %e %b %Y %I:%M %p'); // e.g. Tue, 30 May 2017 2:49 pm

**Comment by markn86** [comment]
Working on this now, bit late, but better than never. :) Plan to get it done this week.

**Comment by markn86** [comment]
Things I am going to do -

1) Add option to use the course start/end date.
2) Add option to use your own specified format as Tim mentioned above.

**Comment by markn86** [comment]
I've ended up not going with the ability to specify a format after discussing with others at HQ. Majority of teachers (99.9%) will have no idea what format to use. I could lead them to the docs strftime but even that could be too complex. I went with the approach of actually including all the formats that are in langconfig.php, and one of them matches the date format you are after Tim.

**Comment by markn86** [comment]
Ok guys, have created a commit that addresses the original issue, closing this. If you still have an issue you want addressed please create a separate issue.

I will release the fix for 3.3 and 3.2 tomorrow in the plugins DB.

Note - I am not longer supporting version 3.1 of this plugin as Moodle 3.1 is no longer supported.
