### ISSUE TITLE
permission mod/customcert:view is not working

### ISSUE THREAD

**Issue by grantcolin** [markn86/moodle-mod_customcert#300]
Hello. The permission :

View a custom certificate
mod/customcert:view

Does not seem to be working in version 3.7.1 (2019052001) on Moodle version 3.7.1

**Comment by markn86** [comment]
What seems to be the issue? I had a brief look at the code and found it listed at https://github.com/markn86/moodle-mod_customcert/blob/MOODLE_37_STABLE/view.php#L44.

**Comment by grantcolin** [comment]
Hello Mark The "view certificate" button is missing for users with the permission mod/customcert:view = allow

**Comment by markn86** [comment]
Ah, sorry. This was changed in #270, see https://github.com/markn86/moodle-mod_customcert/commit/8358280c6c30c5eed4cee061fc71001df29ab1a0 where the capability is given to students by default.

**Comment by grantcolin** [comment]
ok thanks. If it seems that "view certifcate" permission no longer works unless the user also has student role. Once I added this role the view certificate button re-appears.

**Comment by markn86** [comment]
Thanks, closing. This is intentional behaviour.
