### ISSUE TITLE
Поддержка "кириллицы" (UTF8)

### ISSUE THREAD

**Issue by ikt-admin** [markn86/moodle-mod_customcert#305]
Добрый день!

Наша школа использует moodle уже пять лет.
Установили ваш модуль.
Работает замечательно, модуль отличный.
Но возникли две проблемы:
-при сохранении сертификата создается файл "pdf" , без имени только расширение, на почту отправляется нормально с именем и расширением;
- при формировании сертификата "кириллица" отображается "???????????".

Подскажите пожалуйста как решить эту проблему.

С уважением, Александр.

**Comment by markn86** [comment]
Sorry, are you able to create this issue in English (or check the forums for support)?
