### ISSUE TITLE
TCPDF error when trying to view certificate from profile page

### ISSUE THREAD

**Issue by yvanleduc** [markn86/moodle-mod_customcert#306]
Moodle 3.5.6+ (Build: 20190628)
Custom certificate version 3.5.7  (2018051708)

When an admin want to see the certificates issued for a user from his profile page we get an error:

__Exception - TCPDF ERROR: Some data has already been output to browser, can't send PDF file

×Debug info: Error code: generalexceptionmessage

×Stack trace:

line 2927 of /lib/tcpdf/tcpdf.php: Exception thrown
line 7653 of /lib/tcpdf/tcpdf.php: call to TCPDF->Error()
line 190 of /lib/pdflib.php: call to TCPDF->Output()
line 311 of /mod/customcert/classes/template.php: call to pdf->Output()
line 59 of /mod/customcert/my_certificates.php: call to mod_customcert\template->generate_pdf()__

Thank you for helping

**Comment by markn86** [comment]
Sorry, I can not replicate this.

The steps I took were -

1. Add certificate to a course.
2. Log in as a user in that course.
3. Download the certificate.
4. Log in as the admin.
5. Visit the user's profile in step 2.
6. Click on 'My certificates'.

Am I missing something?

Also, please see #218 as it may be related.

**Comment by yvanleduc** [comment]
WE solved the problem...debug mod was on that's why we had this error
message.

Thank you

Le mar. 8 oct. 2019 à 14:44, Mark Nelson <notifications@github.com> a
écrit :

**Comment by markn86** [comment]
Great! Cheers. Closing this now.
