### ISSUE TITLE
Add ability to configure requiredtime for each course

### ISSUE THREAD

**Issue by n-se** [markn86/moodle-mod_customcert#307]
Currently it is only possible to configure the required minutes in course globally and not individual per course.
It would be nice to have the ability to configure this for each course individually.

**Comment by markn86** [comment]
Sorry, I am confused. When you add the activity you get to choose the required time. This is for the course you are adding it on. Are you asking that it can be set to another course than the one it is added in?

**Comment by n-se** [comment]
Looks like I missed this option, there is the global option `customcert | requiredtime` and an individual option for the activity. So this issue can be closed but would you be so kind and explain the difference between these two options? Is the global option just the default if no required time is set in the activity?

**Comment by markn86** [comment]
That is correct. Thanks for addressing this and closing the issue.
