### ISSUE TITLE
Invalid course module ID

### ISSUE THREAD

**Issue by llssite** [markn86/moodle-mod_customcert#34]
When I click on get your custom certificate I get the following error Invalid course module ID.

Version: 3.1 release (Build: 2016052302)

**Comment by markn86** [comment]
Hi, thanks for the report.

What is the page you are viewing? mod/customcert/view,php?

**Comment by llssite** [comment]
View.php
By the way thank you for the amazing quick reply.


Sent via the Samsung Galaxy Note5, an AT&T 4G LTE smartphone
-------- Original message --------From: Mark Nelson <notifications@github.com> Date: 8/29/16  22:06  (GMT-06:00) To: markn86/moodle-mod_customcert <moodle-mod_customcert@noreply.github.com> Cc: llssite <llsadmin@legacylearningsolutions.net>, Author <author@noreply.github.com> Subject: Re: [markn86/moodle-mod_customcert] Invalid course module ID (#34) 
Hi, thanks for the report.

What is the page you are viewing? mod/customcert/view,php?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/markn86/moodle-mod_customcert","title":"markn86/moodle-mod_customcert","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/markn86/moodle-mod_customcert"}},"updates":{"snippets":[{"icon":"PERSON","message":"@markn86 in #34: Hi, thanks for the report.\r\n\r\nWhat is the page you are viewing? mod/customcert/view,php?"}],"action":{"name":"View Issue","url":"https://github.com/markn86/moodle-mod_customcert/issues/34#issuecomment-243320379"}}}

**Comment by llssite** [comment]
Sorry about the included text from the email... :)

**Comment by markn86** [comment]
Thanks!

So the error is happening because of https://github.com/markn86/moodle-mod_customcert/blob/master/view.php#L37 and unfortunately there is not much I can do in terms of code to fix this. It is basically say that the module does not exist in the database (for whatever reason). Has this been a custom certificate you have been using before that no longer works, or one you just created? It would be great if I could get some replication steps.

**Comment by llssite** [comment]
It's one we have been using. Did a update for Moodle and the certificate module over the weekend. Just had a user report it today though.

**Comment by llssite** [comment]
It's one we have been using. Did a update for Moodle and the certificate module over the weekend. Just had a user report it today though.

**Comment by markn86** [comment]
When you say certificate module, do you mean mod_certificate or mod_customcert (you can tell by looking at the URL if it's mod/certificate/view.php or mod/customcert/view.php)? Either way I can't explain why the module would suddenly no longer exist on the site after an upgrade, yet still display in the course. Seems that something messed up somewhere. If a user has reported it, are you also able to reproduce it?

**Comment by llssite** [comment]
Sorry about that, it is the customcert. Yes, as logged in as the administrator I get the invalid ID error as well. I also get the error when I attempt to download a previous certificate from another user. I'm not sure what happened either. :) I checked in the database and there seems to be the right information stored in the tables. Either way, I am restoring from a backup now. Although, if the same happens after I run git pull to update...here's hoping. :)

**Comment by llssite** [comment]
Well, not sure what is causing the problem, but it has something to do with the update process. I have another "test" site up on another domain where I first tested mod_customcert before putting it on our live site. I tested the viewing of a certificate before the update and was able to view it just fine, once I applied the update, I started getting the "Invalid course module ID". If you need anything or would like me to dump my "test" database, please let me know.

**Comment by markn86** [comment]
Are you updating the customcert, or the Moodle version? If it's the customcert, what version are you upgrading from?

**Comment by llssite** [comment]
I am updating the customcert and the version I'm updating from is Beta release (Build: 2016021900).

**Comment by markn86** [comment]
Ok, so you would have installed from the release https://github.com/markn86/moodle-mod_customcert/commit/43d20c0d1b7a3f93eb292f15b282d2909f349073. This was before I was upgrading the database with any changes I made because it was still in beta, sorry. Are you able to turn on debugging mode (see https://docs.moodle.org/31/en/Debugging) to provide me with the full strack trace?

**Comment by markn86** [comment]
The only DB change I performed since changing the plugin to Beta was https://github.com/markn86/moodle-mod_customcert/commit/6889b04df0803c448f38fb5e70506dffe32640bf.

**Comment by llssite** [comment]
I knew I was taking a chance when using the beta version, I was just really loving how easy this module is to use to create a custom certificate. Thank you for taking the time with me!

Here is the stack trace:
Stack trace: 
•line 1502 of /lib/dml/moodle_database.php: dml_missing_record_exception thrown
•line 1478 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()
•line 293 of /mod/customcert/element/grade/classes/element.php: call to moodle_database->get_record()
•line 273 of /mod/customcert/element/grade/classes/element.php: call to customcertelement_grade\element::get_mod_grade()
•line 129 of /mod/customcert/element/date/classes/element.php: call to customcertelement_grade\element::get_grade()
•line 299 of /mod/customcert/classes/template.php: call to customcertelement_date\element->render()
•line 127 of /mod/customcert/view.php: call to mod_customcert\template->generate_pdf()

**Comment by markn86** [comment]
No problem!

It seems the grade element is pointing to a course module that no longer exists. If you edit customcert and then the grade element and re-select the grade item it displays the grade for then it should work as expected. Will have to fix it so the customcert doesn't explode when this happen.

**Comment by llssite** [comment]
Alright, if I understand correctly, I should modify the certificate and change the grade for the course? Or do you mean something else? :)

**Comment by markn86** [comment]
Nope. Just re-edit the custom certificate and edit the grade element you added to it, then under 'Grade item' select the grade item you want and then click on 'Save changes'.

**Comment by llssite** [comment]
I never had a grade element added to the certificate. I did try and add one and selected the grade item as the course, although I am still getting the same error with the same stack trace.

**Comment by markn86** [comment]
Ahh, nevermind. I look at the the stack trace incorrectly. It is because the date element is using a function in the grade element that is trying to find a course module that does not exist. Ok, replace everything I said earlier with 'date' rather than 'grade'.

**Comment by llssite** [comment]
Alright, it worked! You are awesome! I will update my module on my live site today, if all goes well, your solution will fix my problem there as well.

I do have a question, when editing the element I noticed that the Position X and Y is no longer present. How do you reposition the elements?

**Comment by markn86** [comment]
Glad I helped! :) You can drag and drop the elements by clicking on the 'Reposition elements' link under the table. It should really be more noticeable. Will be addressing the UX experience in #35.

**Comment by llssite** [comment]
Thank you!

**Comment by markn86** [comment]
Reopening just to remind me to fix this when a course module is missing. :)

**Comment by ShelterJames** [comment]
I had the same problem on Moodle 3.0, and fixed it simply by editing the date element. Thanks.

**Comment by markn86** [comment]
Fixed.
