### ISSUE TITLE
Create a block to verify custom certificates

### ISSUE THREAD

**Issue by Amaroaln** [markn86/moodle-mod_customcert#36]
Hi,

I'm looking for a plugin that works like a block verify certificates issued with Custom Certificate. 

The plugin Block Verify Certificate doesn't work with Custon Certificate.

The codes issued in Custom Certificate certificates are not recognized in Block Verify Certificate .

Thank you

**Comment by markn86** [comment]
Hi,

Sorry, there currently isn't but it certainly would be a good idea to create one. This would obviously take me some time to do as I would want to first review the code from https://moodle.org/plugins/block_verify_certificate then add my changes. It may be quicker in the meantime to download the existing block and change the SQL queries to point to the customcert table.

**Comment by markn86** [comment]
Functionality will exist in #51.
