### ISSUE TITLE
Add sorting to the report

### ISSUE THREAD

**Issue by BuddyEthridge** [markn86/moodle-mod_customcert#4]
Mark,

We have not installed the newest version yet, but one of the issues our users pointed out with the original was the lack of sorting or searching in the reports area.  In the old version, when using the "view xxxx issued certificates", the list shows up in alpha order by user first name, with only the numeric page method of navigation.  Our users would like to be able to sort/choose by first letter of first and/or last name or even search specifically by username.

Thanks for all your work on this project.  It is a great addition to Moodle.

**Comment by markn86** [comment]
Converting the existing html_table to a table_sql instead which supports exporting as well as sorting. Should be done tomorrow.

**Comment by markn86** [comment]
Sorry, just realised this issue also included searching. I plan on doing quite a bit of dev work on this module this week but I want to focus on more than just the report - so have reduced the scope of this issue. I think for the most part users will be happy being able to sort by name to find the user, but for future usage it would be nice to be able to search for students as well. I created #31 to deal with that.

**Comment by markn86** [comment]
Done. Closing.
