### ISSUE TITLE
Label on the "get your custom certificate" button

### ISSUE THREAD

**Issue by JosiahCarberry** [markn86/moodle-mod_customcert#40]
The label on this button should probably be "Get your certificate" and not mention "custom", which is irrelevant from the perspective of the student. Ideally, the label should be configurable.

**Comment by markn86** [comment]
Would simply require changing https://github.com/markn86/moodle-mod_customcert/blob/master/lang/en/customcert.php#L64. I will do that. However, having it configurable will be a more demanding time wise and I have other more urgent dev requests.

**Comment by markn86** [comment]
Done.
