### ISSUE TITLE
Drag and drop not change the position

### ISSUE THREAD

**Issue by robsoncardosoti** [markn86/moodle-mod_customcert#42]
![draganddrop](https://cloud.githubusercontent.com/assets/18193359/18886946/7feb2f44-84c8-11e6-953c-77bd1c767f5f.PNG)
I have the Custom certificate module 3.1 release (Build: 2016052302) in Moodle 3.1.2+ with PHP 7.0 and the drag and drop not work, not change the position the element and not present error message.

**Comment by robsoncardosoti** [comment]
The Width of element is mandatory.

**Comment by markn86** [comment]
Thanks for taking your time to report this issue and come back with an explanation.
