### ISSUE TITLE
Certificate is blank

### ISSUE THREAD

**Issue by kfisher33** [markn86/moodle-mod_customcert#43]
I'm having trouble getting certificate to show in a course. I can add and see it as a preview but when I attempt to generate in a course it comes up blank. I tried uninstall/reinstall, still having the issue. Any ideas?

**Comment by markn86** [comment]
Hi Ken - when you turn on debugging (https://docs.moodle.org/31/en/Debugging) do you get any errors that display on the page?

**Comment by robsoncardosoti** [comment]
I have this problem too. I enable debugs options, but don´t display errors.
PDF is generated only admin page of custom certificate.

**Comment by markn86** [comment]
It would be awesome if I could get some replication steps so I can see this in action. It's hard to fix an issue if you can't replicate it. :)

**Comment by robsoncardosoti** [comment]
Markn,
How i link the custom certificate created with the course? Because i suspect this is problem.
When create a custom certificate and create new activiti of certificate type in course, the certificado of course not identify the tid of custom certificate. 
I resolve the problem of Certificate is blank in Mysql checkin tables mdl_customcert_pages, mdl_customcert_templates and mdl_customcert_elements.
If i have 2 or more custom certs, how configure what custom certificate use in course???

**Comment by robsoncardosoti** [comment]
markn86,
When i create a Custom Certificate by Manage Templates in the Mysql is inserted one row in tables mdl_customcert_pages and mdl_customcert_templates. When i add a Custom Certificate by in the course in the Mysql is inserted one row in tables mdl_customcert, mdl_customcert_pages and mdl_customcert_templates, then if i create a Custom Certificate by Manage Template and after add in the course are created two certificates in the Database and Certificate of couse is printed in blank.
How resolve this problem? How link in the Course the Custom Certificate created in the Manage Templates?

**Comment by robsoncardosoti** [comment]
markn86,
In table mdl_customcert_templates if change the field contextid to 1 the custom certificate of course is presented in manage templates.

**Comment by markn86** [comment]
Thanks! I am going to try replicate this soon.

**Comment by robsoncardosoti** [comment]
Thank you! I am available.
The correct use of the plugin is to create the custom certificate in the course and edit the template in the managed template?

**Comment by robsoncardosoti** [comment]
Im sorry,
I  was create the template in Site Administration -> Plugins -> Plugins Overview -> Settings of Custom Certificate -> Manage templates -> Create Template. With this steps the mdl_customcert table not is inserted. But the correct steps is in the element custom certificado of course and Edit custom certificate.
This problems is solved for me.

**Comment by EllenK936** [comment]
I created a template in Site Administration > Plugins >Activity Modules > Custom Certificate. I added a Custom Certificate to a course, but I don't see a way to select my template, so when I display the certificate, it is blank. How do I tell the course activity to use the template I have created?

**Comment by markn86** [comment]
Thanks, this will hopefully be dealt by #35.
