### ISSUE TITLE
Digitally sign certificates using tcpdf

### ISSUE THREAD

**Issue by robsoncardosoti** [markn86/moodle-mod_customcert#46]
Hello. 
Congratulations for the plugin.
I need to digitally sign certicates. 
You think you can use this code [(https://tcpdf.org/examples/example_052)] in a new element?
I'm trying but i could not.
Thank you.

**Comment by markn86** [comment]
Hmm, I would need to look into this more but I don't see why you couldn't do it in an element. It's just a call to $pdf->setSignature(). Each element plugin has access to the $pdf object in the render() function. The element could also allow you to set the location of the certificate file as well as other information when you add it to the certificate.

**Comment by robsoncardosoti** [comment]
Hi,
I create other element named Signature based in the image element. In code element.php of element Signature add in the function render the lines:

$certificate = 'file://data/cert/tcpdf.crt';
$info = array(
    'Name' => 'TCPDF',
    'Location' => 'Office',
    'Reason' => 'Testing TCPDF',
    'ContactInfo' => 'http://www.tcpdf.org',
    );
$pdf->setSignature($certificate, $certificate, 'tcpdfdemo', '', 2, $info); 

The PDF is generated sucessfull, but with errors in the digital signature. I checked that PDF is change per CUSTOM CERTIFICATE after of digital signature that cause the problem.
In attach contains the PDF file generated that if open in hexadecimal editor is possible to see that after the EOF (pdf end mark) have others texts, apparently the code of php page.

**Comment by robsoncardosoti** [comment]
Hi, I've found out that after `$template->generate_pdf(true);` in moodle/mod/customcert/edit.php (line 212) the others command `echo $OUTPUT->header();` have gone directly to the pdf file, then I put a `exit;` command just after `$template->generate_pdf(true);` and it works fine now. Dou think it would cause any problem? Thank you

**Comment by robsoncardosoti** [comment]
markn86,
A friend create the functions in the code to implement digital signature in custom certificate. I like send the code changes to insert in the original plugin.
How send the contributions?

**Comment by markn86** [comment]
Sorry I did not respond to this earlier.

Is the code available somewhere on github?

**Comment by robsoncardosoti** [comment]
I don't publish in github, but i like send the changes in code. How i send
this changes for you? Email? Describe in github issue?



Em 02/02/2017 06:32, "Mark Nelson" <notifications@github.com> escreveu:

**Comment by markn86** [comment]
Feel free to email me at markn@moodle.com. Cheers!

**Comment by robsoncardosoti** [comment]
Mark,

A new element (signature) based on the image element was created (attached).

Also change the file ../moodle/mod/customcert/edit.php and insert in line
213 after "$ template-> generate_pdf (true);" The "exit;" statement.
OBS: This statement is required to remove the ber error (bit error rate) in
the certificate signature.
This command was added due to a system error that includes html code inside
the pdf. The system continues to issue "echo" s to render the pages of the
system and this ends up reflecting inside the pdf.
This effect makes the digital signature unfeasible because the file is not
exactly the same as the one signed by the system.

Insert function below into file ../mod/customcert/classes/certificate.php
(attached).

# --------- Function inserted to add the digital certificate upload field
    public static function upload_certificatefiles($draftitemid,
$contextid) {
        global $CFG;
        // Save the file if it exists that is currently in the draft area.
        require_once($CFG->dirroot . '/lib/filelib.php');
        file_save_draft_area_files($draftitemid, $contextid,
'mod_customcert', 'certificate', 0);
    }

If the images are not appearing in the certificate elements reset activity
(render html), change line 238 of the file ../mod/customcert/lib.php to:

if ($context->contextlevel CONTEXT_MODULE) {
require_login($course, false, $cm);
--------------------------------------------------------------------------------------------------------------------------------------
238 } else if ($context->contextlevel CONTEXT_SYSTEM &&
(!has_capability('mod/certificate:manage', $context) === false)) {
--------------------------------------------------------------------------------------------------------------------------------------
return false;
}

Note: This effect has not been identified but is related to the PHP version
because the test version used was the 7th installed in the homologation /
production version 5.6
This can be verified because the problem occurs in the test version but not
in the homologation version



Add the commands below in the
mod/customcert/element/date/classes/element.php file to include the course
start date option in the date element:

row 31
31 /**
32 * Date - Start
33 */
34 define('CUSTOMCERT_DATE_START', '-3');
row 57
57 $dateoptions[CUSTOMCERT_DATE_START] = get_string('startdate',
'customcertelement_date');
row 131
131 } else if ($dateitem == CUSTOMCERT_DATE_START) {
132 $date = $COURSE->startdate;
Adicionar no arquivo
mod/customcert/element/date/lang/en/customcertelement_date.php
$string['startdate'] = 'Start date'; _


I changed the date element also to add new formats
/mod/customcert/element/date/classes/element.php

**
 * Helper function to return all the date formats.
 *
 * @return array the list of date formats
     */
    public static function get_date_formats() {
        $dateformats = array();
        $dateformats[1] = '01 de Janeiro de 2016';
        $dateformats[2] = '01 de Janeiro';
        $dateformats[3] = '01/01/2016';
        $dateformats[4] = '01/01/16';
        $dateformats[5] = '01/01';
        $dateformats[6] = get_string('userdateformat',
'customcertelement_date');

return $dateformats;
    }

/**
 * Returns the date in a readable format.
 *
 * @param int $date
 * @param string $dateformat
 * @return string
     */
    protected function get_date_format_string($date, $dateformat) {
        switch ($dateformat) {
            case 1:
                $certificatedate = userdate($date, '%d de %B de %Y');
                break;
            case 2:
                #$suffix =
$this->get_ordinal_number_suffix(userdate($date, '%d'));
                $certificatedate = userdate($date, '%d de %B');
                break;
            case 3:
                $certificatedate = userdate($date, '%d/%m/%Y');
                break;
            case 4:
                $certificatedate = userdate($date, '%d/%m/%y');
                break;
            case 5:
                $certificatedate = userdate($date, '%d/%m');
                break;
            default:
                $certificatedate = userdate($date,
get_string('strftimedate', 'langconfig'));
        }

}


*Sorry about my English.The credits of these codes are from my friend
Carlos Alberto of the Public Ministry of the State of Goiás. Brazil.*





Att.

           Robson Cardoso Vieira


2017-02-03 1:49 GMT-02:00 Mark Nelson <notifications@github.com>:

**Comment by robsoncardosoti** [comment]
Mail send.

**Comment by markn86** [comment]
Great, thanks. Will take a look when I have time to work on this plugin again (this week I am back to working on Moodle core).

**Comment by robsoncardosoti** [comment]
Hello Mark,
Did you receive the email correctly?
Do you have any plans to implement this signature code in the official plugin?

I need to create a custom field in the enrollment of a course so that the candidate can report if there is any temporary disability or locomotive limitation, there is how to do it in the user's registry, but sometimes the limitation is temporary only in the participation of that specific course. What is the best way to request this information in the application?

Best regards

**Comment by robsoncardosoti** [comment]
Hello Mark,
Did you receive the email correctly?
Do you have any plans to implement this signature code in the official
plugin?

I need to create a custom field in the enrollment of a course so that the
candidate can report if there is any temporary disability or locomotive
limitation, there is how to do it in the user's registry, but sometimes the
limitation is temporary only in the participation of that specific course.
What is the best way to request this information in the application?

Best regards


Att.

           Robson Cardoso Vieira


2017-02-06 2:12 GMT-02:00 Mark Nelson <notifications@github.com>:

**Comment by markn86** [comment]
Hi Robson,

Yes I did receive the email but have 1000 and 1 things on my to-do list for this plugin. :)

I don't really understand your question. Is it a user profile field you want to display based solely on if they are in a certain course?

**Comment by robsoncardosoti** [comment]
Ok. I look forward to integrating the digital signature into the plugin.
I need a field in the course registration to inform if the student has
physical limitation.




Att.

           Robson Cardoso Vieira


2017-04-09 0:54 GMT-03:00 Mark Nelson <notifications@github.com>:

**Comment by markn86** [comment]
I am fixing the garbage HTML being inserted at the end of the PDF in #115.

**Comment by markn86** [comment]
I finally got round to looking at the signature code. Are you able to simply provide the mod/customcert/element/signature folder as a zip rather than me trying to decipher it. There also seems to be code related to adding a new date option, this should be a separate issue. Thanks!

**Comment by robsoncardosoti** [comment]
Mark,

The requested file is attached. But for the signature to work the
customcert / edit.php file and customcert / class / certificate.php
(attached) should be changed. The edit.php was changed because after the
signature the pdf was modified and the signature was invalid (maybe
corrected with pr #115). The certificate.php file creates an option to
upload the digital certificate file.


Att.

           Robson Cardoso Vieira


2017-05-31 5:12 GMT-03:00 Mark Nelson <notifications@github.com>:

**Comment by robsoncardosoti** [comment]
Link to files [https://intranet.mpgo.mp.br/share/s/AXXBOSjIS0C2CqAJW8FVBQ](https://intranet.mpgo.mp.br/share/s/AXXBOSjIS0C2CqAJW8FVBQ)

**Comment by markn86** [comment]
Thanks!

Just FYI - I am currently working on #30 at the moment which will including adding the course start and end date as options for the date element, something I saw you were doing in the code you sent a while ago.

**Comment by robsoncardosoti** [comment]
Yes. As I am in Brazil we need specific date format too and I had inserted it into the code.
But as for the date format would be interesting if the user could inform you in the configuration of the date element and not get fixed in the code, but did not have time to implement it.

**Comment by markn86** [comment]
I am looking at adding the signature element now.

Note - with a recent commit (see https://github.com/markn86/moodle-mod_customcert/commit/5c1f1aa812caa3ecfb9608446cfb4300a6ad1c00) I removed the hackiness of using $this->element, so in your code you will need to update your definition_after_data function if you choose to upgrade. Sorry. :)

**Comment by markn86** [comment]
Thanks for providing the code, but with recent changes I have rewritten quite a bit of it. Apologies if this inconveniences you if you choose to upgrade (note I will only putting this in 3.2 and 3.3).

**Comment by markn86** [comment]
Closing.
