### ISSUE TITLE
Add ability to email certificates when they become available

### ISSUE THREAD

**Issue by bilssam** [markn86/moodle-mod_customcert#48]
Hi,
First, Thanks for the module is very useful!
Second, is there a way that the certificate to be emailed to the student (and maybe the teacher) as soon as they meet the requirements, even if they do not click on the certificate? 
I think it would be useful functionality.

Thank you in advance!

**Comment by markn86** [comment]
I agree this would be a useful feature. Going to see what I can come up with in the next two days .. :)

**Comment by c-first** [comment]
I'm very interested in this as well.  Relying on the student to open and print or save the certificate could be problematic at best, and I'd like to automatically recieve a copy of the certificate so I can print them and add them to the individual's file.
Thanks

**Comment by markn86** [comment]
Thanks for your input.

I will add the ability to email the student, the teacher AND email addresses that are manually entered. This will take some time to develop though as I will be working on it in my own time. I have started but there is still some bit to do. Thanks for your patience.

**Comment by markn86** [comment]
Wow, sorry for the spam of commits (grr Github). I am working on the dev branch which I am continually rewriting history on and this is a larger task where I do bits and pieces when I get time.

**Comment by markn86** [comment]
Note to self - view https://github.com/moodle/moodle/blob/master/mod/forum/lib.php#L457 for usage of templates and email.

**Comment by markn86** [comment]
Also am rewriting history and not including the issue number in the commit until it is ready for production so we avoid spamming this issue. Sorry for the noise!

**Comment by markn86** [comment]
Finally got round to finishing this. It was a pretty big patch and I am sure there are some things that could be fixed. Please create separate for issues you find. Cheers!

**Comment by darcom99** [comment]
As course Teacher/Manager Admin.  How do I use this new capability?  I have a student that has completed the Quiz with the required mark but has not "Clicked the Get Certificate" button.  How do I as the administrator generate it on his/her behalf?    Using Moodle 3.1.6 (Build: 20170508).  Custom certificate
mod_customcert 3.1 release (Build: 2016052312).  Thanks.

**Comment by chiioo** [comment]
> As course Teacher/Manager Admin. How do I use this new capability? I have a student that has completed the Quiz with the required mark but has not "Clicked the Get Certificate" button. How do I as the administrator generate it on his/her behalf? Using Moodle 3.1.6 (Build: 20170508). Custom certificate
> mod_customcert 3.1 release (Build: 2016052312). Thanks.

i have this issue as well, can someone tell how to donwload the certificate in behalf student?

**Comment by Markibacsi** [comment]
darcom99 & chiioo

Why not just activate the 'Email students' option in the certificate settings?

Along with this, you could use the 'Restrict Access' settings to activate the generation of the certificate based on a specific score in the quiz.

**Comment by chiioo** [comment]
> darcom99 & chiioo
> 
> Why not just activate the 'Email students' option in the certificate settings?
> 
> Along with this, you could use the 'Restrict Access' settings to activate the generation of the certificate based on a specific score in the quiz.

@Markibacsi 
thank you for the response, it is possible with that wat, but the student need to issued the certificate first then teacher will get the copy right?. what if the student not issued the certificate, but teacher want to get the certificate of that student? is there any way to get it?

**Comment by Markibacsi** [comment]
When you click on the certificate activity as a teacher, there is a list of students that have been awarded a certificate, there is a download link beside each name.

If you want to automate the process... In the same settings as emailing the students, you’ll find an option to email the teacher too.
