### ISSUE TITLE
User field element is no more working

### ISSUE THREAD

**Issue by jmvedrine** [markn86/moodle-mod_customcert#5]
Hello Mark,
As mod/customcert/element/userfield/lib.php try to include lib/conditionlib.php and to use condition_info::get_condition_user_fields it is no more working with recent Moodle versions.
But as I don't know how conditionlib was working and how core_availability classes are now working I don't know how to upgrade this code. Can you help ? Thanks. Jean-Michel

**Comment by markn86** [comment]
Hi Jean, this is now fixed on master. Cheers!
