### ISSUE TITLE
Add element name to modal when repositioning 

### ISSUE THREAD

**Issue by jeffvee** [markn86/moodle-mod_customcert#53]
When you're positioning the elements it's hard to tell similar ones apart from ones that aren't obvious.  I'd propose to add the element name to the pop-up modal.

**Comment by markn86** [comment]
Agreed.

**Comment by markn86** [comment]
You can see the element name in the form when you open the pop-up dialogue. Do you not think this is sufficient?

**Comment by markn86** [comment]
I think having the name of the element in the dialogue is sufficient.
