### ISSUE TITLE
Ability to include the user response in certificate

### ISSUE THREAD

**Issue by sayron5** [markn86/moodle-mod_customcert#58]
Hi Mark,

Thank you so much for the great Custom Certificate component!  Would it be possible to add some sort of functionality to enable the certificate to display the user response to a quiz field to the custom certificate module?  My situation is this:

We are currently offering courses, but the number of credits awarded is variable according to how long the student participated for. The issue could be addressed using a user profile field, but its cumbersome to update each user's profile with the correct credits (also we will be offering a large number of courses, so a custom profile for each would be unwieldy).  What I would like to do is be able to append a quiz question to the course that would specify the amount of credits they are awarded on an individual basis.  The value in this field could be pulled directly in to the custom certificate.

Another idea:

Inserting values in line with a string of text to Custom certificate is currently a bit ugly.  To my understanding you currently have to position elements on the page and leave gaps in the static text to fit in the dynamic variable.  It would be really nice if there were a way of including macro text or something inline (like %%CourseName%%).

Example Use case:

I'm trying to output a name:

Joan Smith, APN, AOCN, MPN

This is actually a combination of the name field and a user field for their credentials.  It would be nice if I could do something like:

{Username}, {Credentials}

Another potential feature that helps with the inline issue would to have the Userfield element (and other elements where it makes sense) have prefix and postfix fields that allow the user to specify static text before and/or after the field.  (It doesn't solve the compound field issue, but its a start!)

Thanks!

--Frank

**Comment by markn86** [comment]
For the response to a quiz question you could add another element (mod/customcert/element/xxx) to the custom certificate plugin that displayed this data for you. It is quite a specific request and not something I will be working on anytime soon unless it becomes a popular demand by the community.

Regarding a combination of fields - that sounds like a bit of work and I can't imagine working on that anytime soon as there are more pressing bugs to fix! Unfortunately at this point in time you will have to keep adding the necessary fields to your certificate then positioning them correctly.

Regarding static text - see #54.
