### ISSUE TITLE
Ability to view students' certificates

### ISSUE THREAD

**Issue by jmvedrine** [markn86/moodle-mod_customcert#6]
customcert is suffering of the same problem that certificate has (but to a lesser degree :-) : in some places it is assumed that the current connected user is also the student for whom the certificate has been issued (for instance a lot of elements use $USER).
This is unfortunate because it preclude doing some things
For instance I wanted to write a course report that would permit teachers to view, delete, download issued customcert. But according to my tests this is not possible, for instance the image printed on all customcert is the one of the teacher !
I wanted to report this for some time but I forgot about this. Recent posts on the same subject but for the certificate module reminded me of this.

**Comment by jmvedrine** [comment]
Oops the example with user picture is wrong, this is my own code not yours. But the problem is present in code, date, grade, student name, userfield

**Comment by markn86** [comment]
Hi Jean,

This is almost certainly still an issue. Just out of interest - are you still using this module?

**Comment by jmvedrine** [comment]
Hello Mark,
No I am almost retired and my Moodle website is living its last weeks ...

**Comment by markn86** [comment]
Sorry to hear that Jean! Enjoy your retirement and thanks a lot for your awesome contributions to Moodle. :)

**Comment by markn86** [comment]
Working on this now. ;) Better late than never hey?

**Comment by markn86** [comment]
Done! Thanks all. :)
