### ISSUE TITLE
Custom user profile fields

### ISSUE THREAD

**Issue by Gotrekk** [markn86/moodle-mod_customcert#61]
It would be nice to get informations from custom user profile fields aswell

**Comment by markn86** [comment]
You can currently do this by adding a 'User field' element to the certificate.

**Comment by Gotrekk** [comment]
yes, i saw the "user field" element... but you can pick a "custom" user field... just regular user fields

**Comment by markn86** [comment]
I just tested then and was able to create a 'Birthday' field as a custom user profile field and then added it to my certificate successfully.

**Comment by Gotrekk** [comment]
my bad... i tried with a "text area" and didn't appear... "text input" works! thanks
