### ISSUE TITLE
Ability for the admin to generate certificates on behalf of users

### ISSUE THREAD

**Issue by Tw0bit** [markn86/moodle-mod_customcert#62]
Is it possible for an admin to generate the certificate at a course level?

**Comment by markn86** [comment]
Sorry, I don't understand the question. Certificates are added to courses.

**Comment by Tw0bit** [comment]
Sorry for the vague explanation. We have a course with the certificates enabled - it works great thanks for the module.

However the certificates are only gemerated when a student clicks on the module link and then clicks generate certificate. Once generated, admins can see them.

For our use case, we ideally would like to be able to generate the certificate as the admin as we need them for the third party training program provider. Currently we login as the student to generate which is time consuming.

So what I was looking for was somehow via the admin panel to view students without the certificate generated and be able to click generate per student as required.

**Comment by markn86** [comment]
Ahh I see. Yes I imagine that would be very time consuming. Is there a reason the students are not downloading the certificate to begin with?

**Comment by markn86** [comment]
Closing this as I believe #48 will solve this.
