### ISSUE TITLE
Add third-party user picture element to core

### ISSUE THREAD

**Issue by markn86** [markn86/moodle-mod_customcert#65]
Jean-Michele kindly developed this for the beta release, but it is now broken in stable. It's a good idea and wouldn't take much time to get it working again.

**Comment by kulinfx** [comment]
Dear Mark,

Hi I tried to work it as per your current sub-plugin structure, I am attaching a zip file as I made it, can you look into it, as I am not a programmer and it is not working even in the new structure.
[studentpicture.zip](https://github.com/markn86/moodle-mod_customcert/files/684360/studentpicture.zip)

Regards

Kulin Shah

**Comment by markn86** [comment]
I have time to do this today. \o/

**Comment by markn86** [comment]
Done.

**Comment by kulinfx** [comment]
Thank you Mark, now I was wondering where should I download the same from ?

**Comment by markn86** [comment]
I am working on a bunch of issues right now that I am aiming to finish by the end of the week.

On Friday afternoon (AWST) I will release a new version of the plugin which you will be able to download at https://moodle.org/plugins/mod_customcert.

**Comment by kulinfx** [comment]
Dear Mark,

Thank you I started with the user picture element as I copied and pasted
the files manually in the folder system.

In reposition element it is showing however, I am unable to yet get it in a
live environment.

Let me try with a few other logins also.

Meanwhile, I tried to copy paste your verify certificate block into the
plugin, it is showing the block, but I guess it is conflicting with the old
certificate module, so it is not verifying, I know that the issue is not
yet solved, so I am waiting for it to get resolved.

Also I am using Moodle 2.9, so kindly make the version of your module
compatible, right now I skirted the issue by editing the version.php file
to old values :)

Regards

Kulin Shah

**Comment by markn86** [comment]
Hi Kulin,

The verification block has nothing to do with me. :) It was written by someone else and is tied directly to the mod_certificate plugin. It doesn't query the same database tables - so will never work with this plugin.

I am dealing with verification in #51 but it will be a part of the activity, and not a separate block.

Unfortunately I am not supporting Moodle 2.9 or 3.0 (as they are no longer supported Moodle versions) but you can simply apply the patches yourself (listed here - https://github.com/markn86/moodle-mod_customcert/commits/master). For the 'userpicture' element you could simply copy that folder (see https://github.com/markn86/moodle-mod_customcert/tree/master/element/userpicture). It *should* work but can't guarantee it as I haven't tried myself.

**Comment by kulinfx** [comment]
Dear Mark,

Thanks for the commit, I have instaleld Moodle 3.2 now.

There is one quirk with the userpicture element, I can see the user picture while editing the certificate, but when the actual certificate is used the certificate is displayed without the userpicture.

Let me tell you I am using a border, i.e. a prefilled certificate design also, so do you think that may be the case ?
[Custom_Xpert (2).pdf](https://github.com/markn86/moodle-mod_customcert/files/750083/Custom_Xpert.2.pdf)

The attached file is the output result of the certificate and I will also attach a screen shot of how the certificate looks like while designing.

![screenshot 2017-02-03 15 37 13](https://cloud.githubusercontent.com/assets/24913286/22587200/b65a15cc-ea26-11e6-95e9-f90333888703.png)

So the user element is being used, however, it is not used while printing, also, the cerify certificate is working while in admin mode only, where as I think it should be there for anyone to verify for e.g. an employer who wants to verify the authenticity of the certificate can do so from the homepage of the site without having to login.

Regards

Kulin Shah

**Comment by markn86** [comment]
Hi Kulin,

Thanks for your detailed report.

I just printed out the certificate and the user picture was present. Note - there is some logic in the element where if the user rearranging the elements does not have a profile picture the default image will be shown, however when displaying the PDF it will not be displayed. This means an admin/teacher can rearrange the elements appropriately without having a profile picture themselves.

Regarding the verification issue, you are not the first to mention this - I have created https://github.com/markn86/moodle-mod_customcert/issues/78.

**Comment by kulinfx** [comment]
Dear Mark,

I have tried a user having a profile picture and then only I reported, so
my question is whether it is the case where I am using a border image as
well as a profile picture so the second element is not printed.

Regards

**Comment by markn86** [comment]
Have you tried changing the order of the elements?

**Comment by kulinfx** [comment]
I have tried it, when I put the userpicture element first then the border
element doesnt display, when I put the border element first ,then the user
picture displays but then it doesnt print, it only prints the border
element and rest of them, would you like to view  it with my admin rights ?

**Comment by markn86** [comment]
This is odd. I just tested on my system and a user picture and background element both printed.

I don't like the idea of gaining admin access to a site that isn't mine, so please *don't* give me any important details. :)

If you could create another issue at https://github.com/markn86/moodle-mod_customcert/issues (we are polluting this issue too much) that lists step-by-step instructions in order for me to replicate the error that would be great.

Thanks!
