### ISSUE TITLE
Custo cert gives "Course module ID incorrect" error, reproducable

### ISSUE THREAD

**Issue by railpromo** [markn86/moodle-mod_customcert#66]
Dear team

I'm facing a similar issue as mentioned in this thread:
https://github.com/markn86/moodle-mod_customcert/issues/34

I'm using the custom cert module. Once a user completes a test, I see the certificate is issued. It shows up in the list of issued certificates with a download link. Once clicking on the download link, I get the (Dutch version of the) "Course module ID incorrect" error message. The info came from the student and I can reproduce it in my admin role.

The link for the certificate refers to the custom cert module. In the course, I can edit the certificate settings and see it's design, everything is looking fine there.

Do you have any suggestions on where to look to find the cause of this problem?

Looking forward to hearing from you.

Best,
Luc

**Comment by railpromo** [comment]
I did find the cause of the problem. The grade to be displayed is set to the course as a whole, whereas the grade is only assigned to the test. Changing this for all certificates solves the problem.

**Comment by markn86** [comment]
Ok, thanks for letting me know. Will address this in #34 also.
