### ISSUE TITLE
View all certificates - even if student has not viewed the individual certificate on the course page yet.

### ISSUE THREAD

**Issue by whipper81** [markn86/moodle-mod_customcert#67]
Hi,
It looks like the certificates only appear on the "My Certificates" page after they've been viewed once on the individual courses (After the "Get your certificate" button is clicked). Is it possible to allow the certificates to be viewed on this page if the student has not clicked that button the course page?

Students are expecting to see certificates on this page since they successfully passed the course, but only the ones that were already viewed show here. That's a bit confusing. Is there a way around that?

**Comment by markn86** [comment]
I am going to close this as #48 will allow you to achieve this result by automatically emailing (and issuing) the certificates.

Currently a certificate has to be issued in order to appear on the 'My certificates' page. This will not change. I don't like the idea of checking every single certificate on the course and checking if the user has access to it, and if so displaying it.

**Comment by whipper81** [comment]
OK thanks. That will be useful going forward.

 Here's my issue that maybe you can help with. I have a new Moodle site that has data imported from a different system.  This includes thousands of users that have already completed courses. I imported the grades for the activities for these users. Is there a way to programmatically, or perhaps by using the database, generate the certificates so they will appear for the users? I don't want to log in as the student and click "Get Certificate" for every student's passed activity, and I don't want to have the student need to do that either.

**Comment by markn86** [comment]
#48 will achieve that. You would simply create the certificate and then when the site cron is run it will email these out and issue them. When you say 'generate the certificates so they will appear for the users' where did you want these to appear? Do you mean via email or in the course?
