### ISSUE TITLE
This blank certificate is driving me insane...

### ISSUE THREAD

**Issue by Skyedesign** [markn86/moodle-mod_customcert#69]
I've gone through the previous posts about the blank certificate but unfortunately I can't quite understand what some of the guys are talking about. This is the most obtuse thing I have ever experienced.

Creating Template.

1. Click manage templates
2. Click create template
3. Name the template: HIV
4. Use default settings for width and height, margins
5. Add element: Background Image (Edit element window opens)
6. Upload image in A4 size PNG format.
8. Click save changes (Edit element window closes)
- Return to Edit custom certificate window
9. Edit Background Image element (Edit element window opens)
10. Select uploaded image (this can't be done without saving it and then reloading the element)
11. Save changes (Edit element window closes)
- Return to Edit custom certificate window
12. Add element: Student Name (Edit element window opens)
13. Save changes (Edit element window closes)
- Return to Edit custom certificate window
14. Add element: Date (Edit element window opens)
15. Save changes (Edit element window closes)
- Return to Edit custom certificate window
16. Click re-position elements (Reposition elements window opens)
17. Drag elements over blank spaces in background image.
18. Click save and close (Reposition elements window closes)
- Return to Edit custom certificate window
19. Click save changes and preview
19. Blank page.

Create a topic: Certification (at end of course)
Create certificate.

1. Add an activity > select custom certificate > click add.
2. Enter name of certificate: HIV Aware
3. Enter description of certificate: For competence in the HIV Awareness course.
4. Set duration to 10 minutes. Restrict 'Modify' and 'Copy' of PDF.
5. Set Restrict Access to Student must have Course Total ≥ 80%.
6. Select Do Not Show Activity Completion.
7. No tags.
8. No competencies.
9. Click save and return to course

Adding Template to Certificate.

1. Administration > Custom certificate administration > Edit custom certificate.
2. I see my certificate HIV Aware with no content.
3. I see my template: HIV
4. Load template: HIV (page reloads)
5. I see my certificate with the template elements and settings now loaded.
6. Save changes (page reloads)
7. Save changes and preview...
8. Blank screen.
9. Reposition elements (all elements present and correct)
10. Save and close (Reposition elements window closes)
- Return to Edit custom certificate window

As Student complete the course. Make sure I take 10 minutes. get 100%.
I am awarded the certificate.
Download certificate.
Blank.

As Adminstrator browse to topic Certification.
I see 1 certificate awarded.
Download certificate.
Blank.

Either the instructions are omitting something very fundamental or I'm just incapable of following the logic of assigning certificates to a course after completion.

This is very urgent, please help!

**Comment by markn86** [comment]
Solution - re-edit the activity's date element and re-save once the correct date element has been chosen (it may already be selected when you visit the page so simply just save the form element again).
