### ISSUE TITLE
Add mobile app support

### ISSUE THREAD

**Issue by simorghgroup** [markn86/moodle-mod_customcert#70]
Hello
I wanted use this module in the mobile App. Is there a solution to this issue, or you can do it for the mobile app?
Thank you

**Comment by markn86** [comment]
This would require some work.

See the last few commits in https://github.com/markn86/moodle-mod_certificate/commits/master by Juan Leyva. There is quite a bit of work involved.

**Comment by markn86** [comment]
@jleyva

**Comment by markn86** [comment]
This is for Moodle Mobile v3.5.0 (not to be confused with your Moodle site version) and will not work on Mobile versions earlier than this.

If you are running a Moodle site on version 3.4 or below you will need to install the local_mobile plugin in order for this to work.

If you are running a Moodle site on version 3.0 or below then you will need to upgrade.

Note - Ignore the commit spams above, this was done on a dev branch.
