### ISSUE TITLE
Template name field too short in the database

### ISSUE THREAD

**Issue by anieminen** [markn86/moodle-mod_customcert#71]
Hi,

Custom certificate template 'name' field is only 40 characters long in the database table `customcert_templates`. Is there a specific reason for this? There is no character limit for the name field in the editing form, and trying to save a template with a longer name throws database exception: `Data too long for column 'name'...`

**Comment by markn86** [comment]
Good point. No real reason to have it that short. I will extend it and add some validation to the form to prevent people breaking it by entering too many characters.

**Comment by markn86** [comment]
You can also get a DB error from long element names as well.

So, in this issue I am going to extend the length of the 'name' column for templates to 255 and add validation for template and element names to avoid a DB error.

**Comment by markn86** [comment]
Done.
