### ISSUE TITLE
Certificate is not printing user image

### ISSUE THREAD

**Issue by kulinfx** [markn86/moodle-mod_customcert#80]
Dear Mark,

I have a Certificate uploaded and am using it as a border image as a background to the certificate I need to print. When I am using that and a user picture it does not print the user picture however, it shows the user picture while in reposition element.

Could it be a permissions issue to other users ?

Or it could be simply a clash between picture elements ?

What I am doing is create 

- Create a new custom certificate
upload a new image to be used as a border image / background image
use the userpicture element
customize the certificate using reposition element
save the changes

login as a user with a profile picture
print the certificate -( but it does not print the user picture )

-

**Comment by markn86** [comment]
I actually experienced this issue myself without trying to replicate the problem. Will work on a fix. :)

**Comment by markn86** [comment]
Done.
