### ISSUE TITLE
Moodle 3.1, activity not showing up for students

### ISSUE THREAD

**Issue by frumbert** [markn86/moodle-mod_customcert#81]
I'm seeing the "Sorry, this activity is currently hidden" text.

I've added the activity to a course and set it's visibility to show, no restrictions, required minutes=0, no completion tracking, and set up and tested the certificate itself as admin. I've checked the permissions against a student and seen that they have mod/customcert:view -> yes. If I enter the url directly for the instance [as a student] then I'm told that the activity is hidden. The record in mdl_course_modules shows that it is not hidden.

In `view.php`, it performs `require_login($course, false, $cm);` - if I `print_r($cm)` I get

    [cm] => stdClass Object
        (
            [id] => 24
            [course] => 8
            [module] => 23
            [instance] => 1
            [section] => 11
            [idnumber] => 
            [added] => 1486600884
            [score] => 0
            [indent] => 0
            [visible] => 1
            [visibleold] => 1
            [groupmode] => 0
            [groupingid] => 0
            [completion] => 0
            [completiongradeitemnumber] => 
            [completionview] => 0
            [completionexpected] => 0
            [showdescription] => 0
            [availability] => 
            [name] => First Aid Certificate
            [modname] => customcert
        )
(but i guess since that property is dynamic, it won't show on a print_r? not sure how to show it's actual value).
requrie_login checks `if ($cm && !$cm->uservisible) {` in order to throw to the activity hidden error message, so I'm wondering why `uservisible` isn't being set on $cm.

a workaround, modifying $cm to give it a value, doesn't work, e.g.
`$cm->uservisible = $cm->visible;`

Moodle 3.1.1+ (Build: 20160811)
Plugin version https://moodle.org/plugins/pluginversion.php?id=13159

**Comment by markn86** [comment]
Hi Tim,

Sorry, can't help you with this one. This is an issue with your Moodle site and I suspect there is something going on that has nothing to do with the custom certificate. The code used here is the same as other modules. Have you purged your site caches? Is the section hidden?
