### ISSUE TITLE
Problem with viewing PDFs from "My Certificates" page for elements with course data

### ISSUE THREAD

**Issue by whipper81** [markn86/moodle-mod_customcert#82]
Hi, you asked me to post here from the Moodle forum about this bug.

PDFs downloaded from the "My Certificates" table don't display course data properly.

The certificates contain a mix of static text, user data, and course data. However the data related to the courses is not showing. Category name, Course name, and a custom element field we added for "credits". The Category name and Course name fields are simply showing the Moodle site title, while the "credits" field is just blank. 

However, when a user downloads the same certificate from the individual course activity page, it works just fine, with all fields displaying properly.

I think I've narrowed it down to the fact that you're calling a global $COURSE variable to retrieve course data for the elements during rendering, but the global $COURSE variable is basically empty on the My Certificates page.

**Comment by tluger** [comment]
We also just noticed that the my certificates page has an issue with populating user and course data correctly.  I think we may be a version behind in the plug-in. Is this an issue that was resolved in the latest release?

**Comment by markn86** [comment]
Nope, this has not been resolved, however, some good news - I am planning on working on it today. :)

**Comment by markn86** [comment]
This has been fixed in master. Will backport to the 3.3, 3.2 and 3.1 branches and release on plugins DB at the end of the week.
