### ISSUE TITLE
Pop-up when downloading certificate

### ISSUE THREAD

**Issue by almighty-grim-reaper** [markn86/moodle-mod_customcert#83]
We really like the plugin and we are using it a lot (2.9/3.0 release (Build: 2016032201)).
There is one strange behaviour we noticed though and it's that there is a pop-up window opening anytime you download a certificate in Chrome or Firefox. Is there a specific reason for this?

I had a quick look through the code and found that by simply commenting out line 102 in the view.php everything works fine without the unnecessary pop-up showing up.

`//$downloadbutton->add_action(new popup_action('click', $link, 'customcertpopup', array('height' => 600, 'width' => 800)));`

Our little problem at the moment is that our hosting provider does not permit us to apply custom code changes and only installs official releases of plugins.

If this pop-up is not a feature, is there maybe a way to disable it in the next release so that a press on the download button downloads the certificate straight away?

**Comment by markn86** [comment]
Thanks for creating this issue. Will have to look into this when I get time. You may be right. I can't see any use of this particular function.

**Comment by markn86** [comment]
Done, thanks for the report.

**Comment by markn86** [comment]
I should also mention that 2.9 and 3.0 are no longer supported Moodle versions, which means I am not supporting them either (I work on this in my spare time and if I supported every single version it would be very time consuming). I would suggest upgrading to Moodle 3.2 asap. :)

**Comment by almighty-grim-reaper** [comment]
Thank you so much for looking into this and fixing it so fast.
I totally understand that you can't keep supporting every version of Moodle for a simple spare time project. This fix would however solve a ton of problems for us and having an official 2.9 release with this fix implemented & available on moodle.org would enable us to get it updated via our hosting provider.
We are quite a big charity organisation and since we are using Totara which is build on Moodle 2.9 and are not planning on upgrading for quite a long time there is unfortunately no other way of doing it.

We do realise however that this will take up quite a bit of your time and to make it worth your while we are therefore obviously more than willing to pay for this extra bit of development if it can be released in a timely matter.
