### ISSUE TITLE
Add separate capability in order to view course report

### ISSUE THREAD

**Issue by pavlorenc** [markn86/moodle-mod_customcert#85]
I found issue in capabilities:

1. If customcert:viewallcertificates is disabled for role, the role can still view the certificates of others.
2. If customcert:manage is disabled for role, the role cant view the certificates of others.

My Case:
I want to create a role for course Supervisor - The Supervisor can view all certificates in course but cannot manage certificates (edit elements etc).

**Comment by markn86** [comment]
Thanks for the report Pavel.

**Comment by markn86** [comment]
Hi Pavel,

Ah, this is via the report.php page, not the my_certificates.php page, right?

The 'customcert:viewallcertificates' capability was introduced for the my_certificates.php page which you can access via your profile. Eg. you view a user's profile and if you have that capability you can click on the 'My certificates' link to view the certificates the user has been issued. This is a site wide setting.

The 'customcert:manage' capability is used in the module context and is not related to the 'customcert:viewallcertificates' capability.

I think the best approach to your situation is to add another capabality, eg 'viewreport' that you could then provide the supervisor. Thoughts?

**Comment by pavlorenc** [comment]
Hi Mark,
yes, I facing this issue in report.php (resp. top-right link in view.php).
Exactly! Add some capability to view issued certificates in one page -which I can provide to supervisor role- eg. 'Viewreport' you mentioned.

**Comment by markn86** [comment]
Ok, thanks Pavel. I have renamed the issue so it is more accurate as the existing capabilities were behaving as expected.

**Comment by markn86** [comment]
Working on this now.

**Comment by markn86** [comment]
Done. Will release fix to plugins DB shortly.
