### ISSUE TITLE
Certificate number and date of registration

### ISSUE THREAD

**Issue by Zell1000** [markn86/moodle-mod_customcert#86]
Ciao Mark,
Prima di tutto grazie per questo splendido plug-in.
Vorrei chiederti se è possibile numerare i certificati rilasciati.

Quindi come elemento certificato numero "xx".

Naturalmente il numero deve essere incrementale relativamente ad ogni corso...

Ed anche la data di iscrizione dell'utente.

Spero tu possa aiutarmi.

Grazie

---------------------

Hi Mark,
First of all thank you for this beautiful plug-in.
I would like to ask you if you can number issued certificates.

So as an element certificate number" xx" .

Of course, the number must be incremental relative to each course ...

And also the user's entry date.

I hope you can help me.

Thank you

**Comment by markn86** [comment]
If you want a specific number you can use the text field. What other number would you like to display? Would you want a number for the certificate itself, or a different number for each issue of the same certificate? What do you mean by user's entry date? To the course? Do you mean enrolment date?

**Comment by Zell1000** [comment]
For the numbers of the certificate code, I mean numbers Release Code. Or "1", "2", "3" ... In order to know how many Certificates of a specific course have released over one year for example, as certificates will make them to generate the same user as soon as he finished the final exam.
I mean the date as the date of user registration to the Course


Forgive me for the bad English.
I understand it is difficult to understand a question of technical expressed in so badly

**Comment by Zell1000** [comment]
Salve Mark.
Qualche novità per me?
Ti allego immagini dell'attestato che intento fare, ho segnato in rosso quello che mi interessa, magari capisci meglio.
![attestato](https://cloud.githubusercontent.com/assets/25792116/23802491/db5ebfe6-05b3-11e7-8671-962b1cf8f2b4.png)
![attestato2](https://cloud.githubusercontent.com/assets/25792116/23802492/db64713e-05b3-11e7-993a-24fa19af0ec6.png)



-------------------------------------


Hi Mark.
Some news for me?
I am attaching pictures of the attestation That rate intention, I marked in red What interests me, Maybe you know better.

**Comment by markn86** [comment]
It is entirely possible to write a plugin that can do this for you or to perform the SQL queries to find out, but I am not going to include it in the plugin as it is very specific and don't think it would be widely used.

**Comment by Zell1000** [comment]
Ok. Grazie mille! Infatti mi sono fatto aiutare da un amico programmatore per fare questo lavore e sembra funzionare (ancora è in fase testing). Ora però ho lo stesso problema che hanno molti altri sulle date.... overro sul certificato mi funziona solo la data di rilascio e non altre date (es. Data di Quiz o data di Completamento del Corso). In caso apro una richiesta.
Grazie ancora per il tuo lavoro! 
-------------------------------------------------------------------
Ok. Thanks so much! In fact I did help from a programmer friend to do this work and it seems to work (still being in phase testing). Now, however, I have the same problem that many others have on the dates .... overro on the certificate I only work on the release date and not other dates (eg Quiz Date or Completion Date of the Course). If I make a request.
Thanks again for your work!
