### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by jorgensendaniel** [markn86/moodle-mod_customcert#87]
Hi Mark

Thank you so much for this fine plugin! 

I've got 2 questions.

I'm not able to change the dateformat on the certifcate to match the danish format.. Would it be possible to do that?

Secondly, I need the possibility to send the certificate via email.. Would that be possible in the future?

Thanks in advance!

Kind regards

Daniel

**Comment by markn86** [comment]
Hi Jorgen,

1) Can you comment on #30? I am not sure what the date format is in Denmark either. :)
2) Sending via email is being done in #48. Keep a look out there.

Cheers!

**Comment by jorgensendaniel** [comment]
Perfect... Thanks :-)
