### ISSUE TITLE
Some images do not appear when generating PDF

### ISSUE THREAD

**Issue by scyrma** [markn86/moodle-mod_customcert#89]
The background picture element works fine in the "reposition" view, but the image does not appear in the final PDF.

**Comment by markn86** [comment]
Yep, can confirm this is an issue. Working on fix now, cheers!

**Comment by markn86** [comment]
I can only replicate this issue if I use a .svg. Was this the filetype you were using as well or was it another? Thanks.

**Comment by markn86** [comment]
The reason I ask is I would like to create a fix for all file types, not just one. What would be even better is if you attached the image you were trying to use! :)

**Comment by scyrma** [comment]
Yes, i think it was an svg.

**Comment by crmpicco** [comment]
I appear to be having the same problem with the PNG below.

![border](https://cloud.githubusercontent.com/assets/2536923/23645449/1545390c-0347-11e7-82d5-c63e48ec441e.png)

**Comment by markn86** [comment]
Thanks for that.

This is also an issue with the 'image' element. However, you can ALSO get the TCPDF error 'Unable to get the size of the image' if you do not specify a width or height for the image. The 'bgimage' element uses the width and height of the PDF so you don't get this error, but the 'image' element attempts to calculate the width and height if it isn't specified resulting in the following -

![photo_2017-03-07_15-52-22](https://cloud.githubusercontent.com/assets/783213/23646909/1688528e-034e-11e7-9828-2cd13ff2c4a6.jpg)

**Comment by crmpicco** [comment]
OK, cheers for the explanation. :+1:  I can see that being a problem for cloud users as they may not always enter the image dimensions, or know where to find them.

**Comment by markn86** [comment]
Yep. And even if they do enter it the image won't be displayed. So, it's something that needs fixed.

**Comment by markn86** [comment]
The image supplied works fine for me.

**Comment by crmpicco** [comment]
Does it display on the PDF?

**Comment by markn86** [comment]
Yep. And so does the watermark.png image from the MDL tracker issue.

**Comment by crmpicco** [comment]
We are also use TCPDF 6.2.12.
```
Name: TCPDF
Version: 6.2.12
Release date: 2015-09-12
Author:	Nicola Asuni
```

**Comment by markn86** [comment]
Discovered this was due to a custom file system being used on Moodle cloud. 

SVG images will still be a problem but will deal with that in a separate issue.

**Comment by markn86** [comment]
Thanks all, closing!
