### ISSUE TITLE
The text element does not support multiple lines

### ISSUE THREAD

**Issue by markn86** [markn86/moodle-mod_customcert#90]
When adding a text element with text that appears on multiple lines it ends up displaying the text all on one line, but the user may not want this. We should obey line breaks.

**Comment by kattekrab** [comment]
Yeah - found this a "What the..." moment.
My workaround was to add each line of the paragraph one by one, which isn't great, but got the job done. Making this a text area, that either flows text within a set width, or respects a line break, would be really great.

**Comment by kattekrab** [comment]
Hi! 

That was me in your session today. 

I might see if I can ask one of our devs to provide a fix and a pull request!

Thanks Mark!

**Comment by sarahactiveops** [comment]
hi @kattekrab - are you all at MoodleMoot? Disappointed I couldnt make it this year.

If at all possible, while you are there... we would really (really!) appreciate a fix for the issue where certificates dont back up and restore- if there's any chance that this could be looked at too we would be forever grateful!!!! (issue #172 )

**Comment by kattekrab** [comment]
@marcusboon is taking a look at the line break issue now!!!

Thanks Marcus :-)

**Comment by kattekrab** [comment]
I seem to recall trying `<br />` tags originally and it not working!  
I'll try again.
Thanks all.

**Comment by markn86** [comment]
Closing given it now accepts HTML and a user can use `<br />`. Changing it from `FORMAT_HTML` to `FORMAT_MOODLE` causes the text to move, so that isn't an option either.
