### ISSUE TITLE
Having issues with installation

### ISSUE THREAD

**Issue by ZackAlfakir** [markn86/moodle-mod_customcert#96]
Hello, I hope this is the right place to put in support tickets. 

I'm running `MOODLE_31_STABLE` and I installed this module using 
`git submodule add git@github.com:markn86/moodle-mod_customcert mod/customcert`

It seems to fail as shown here (sorry about the color scheme):
![image](https://cloud.githubusercontent.com/assets/2652713/24571571/141b47c2-1640-11e7-9218-a9bc13581ff9.png)

Any idea what I'm doing wrong or how to resolve it?

**Comment by markn86** [comment]
Hi Zack, you will need to checkout the MOODLE_31_STABLE branch in the mod/customcert directory.
