### ISSUE TITLE
Display all grade items, not just activities in a course

### ISSUE THREAD

**Issue by pixliacik** [markn86/moodle-mod_customcert#98]
I tried your version for 3.1 and also for 3.2, but I have problem with categories in grade report. I have course for 4 semesters, so I make catogories:
2016
- 2016H1
- 2016H2
2017
-2017H1
-2017H2

In version for 3.1 I can choose the right category name, but the grade shown is not good. In new version I cannot see the this option to select category from grade report...

I need to make certificates for each semester.

**Comment by markn86** [comment]
Sorry for the delayed response. Is this still an issue? Are you using the reports page to download the PDF?

**Comment by pixliacik** [comment]
I have still this problem. When I add "grade"element, I can choose only activites from sections now.

**Comment by markn86** [comment]
Ok, got round to working on this. Creating a fix now.

**Comment by markn86** [comment]
This is taking longer than expected as I ended up deciding to do a biggish refactor to implement this as nice as possible.

**Comment by markn86** [comment]
Hoping to finish this this weekend.

**Comment by markn86** [comment]
Done. Will be available next release.
