### ISSUE TITLE
Grade item name is not show on the certificate at all

### ISSUE THREAD

**Issue by Jarvil** [markn86/moodle-mod_customcert#99]
Hello,

I have noticed that Grade item name doesn't show up in the certificate at all. Moodle version 3.1.5 mod_customcert 3.1 release (Build: 2016052307) 2016052307

![cert1](https://cloud.githubusercontent.com/assets/15193418/24854052/aabaca7a-1de5-11e7-9523-7cef8219425c.PNG)
![cert2](https://cloud.githubusercontent.com/assets/15193418/24854054/ad330fb0-1de5-11e7-8b7c-85fb6043fd07.PNG)
![cert3](https://cloud.githubusercontent.com/assets/15193418/24854058/aefa4aa2-1de5-11e7-9bd6-f9f84f000d43.PNG)

**Comment by Jarvil** [comment]
Hello,

The grade item name isn't show in the template-side of the plugin, its displayd only after you have selected grade item in the certificate settings

**Comment by markn86** [comment]
Thanks for the report Jarvil and I apologise for my late response. I thought I triaged this earlier.

After reading your last response I can see this is a known issue and is reported in #28.
